### ISSUE TITLE
Meta APIException classes to convert broad exception into specific exceptions

### ISSUE THREAD

**Issue by silentninja** [mathesar-foundation/mathesar#1019]
## Problem
Errors like `IntegrityError` are broad and encompasses specific exceptions which can be found by inspecting `orig` field. So we end up having to use repeating logic to get the specific exception
## Proposed solution

We can have an `APIException` class that can take in an `IntegrityError` for example and in runtime using the magic of `MetaClass` can convert into proper `APIException` class based on the `orig` field. This could be applied for other exceptions too like `DataError`

**Comment by silentninja** [comment]
Blocked by #991

**Comment by mathemancer** [comment]
This won't be relevant with the new RPC endpoints.
