### ISSUE TITLE
Improve failure behavior of constraints endpoint

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#1030]
## Description

This ticket lists many small (somewhat independent) problems with the response of the constraints API when subjected to POST requests containing invalid data.

## Caveats

- I tested the constraints API using the changes for #1026, which I'm presuming will soon be merged.
- I'm not mentioning some of the more obvious failure cases which also have the problems with non-conformant response (e.g. case where the request is missing the "columns" field), because I imagine we'll fix that at a lower level, so as to apply to all endpoints.

## Addition context

- #883
- [API Error Standards](https://wiki.mathesar.org/en/engineering/architecture/api-standards#errors)

## Response schema problems

In the following situations, the API correctly responds with a HTTP 4xx status code, but the response schema does not conform to our error standards.

- ~~Attempting to set a unique constraint for a column which contains duplicate values~~ (now fixed)
- ~~Attempting to set a unique constraint with a supplied constraint name equal to that of an existing table~~ (now fixed)

## Unhandled exception problems

In the following situations, the API responds with a HTTP 5xx status code when it should respond with a 4xx status code and a JSON response body conforming to our error standards.

- Invalid "type", e.g.:

    ```json
    {"type":"foo","columns":[1]}
    ```

- Attempting to set a unique constraint by supplying the id of a column that exists in a different table from the table whose id is supplied in the URL.

- An empty `columns` array, e.g.:

    ```json
    {"type":"unique","columns":[]}
    ```

- Non-existent column id, e.g.:

    ```json
    {"type":"unique","columns":[9999]}
    ```

**Comment by Anish9901** [comment]
Can I work on this?

**Comment by kgodey** [comment]
Sure, go ahead @Anish9901

**Comment by Anish9901** [comment]
@seancolsen can you please confirm the following behavior?
> Attempting to set a unique constraint for a column which contains duplicate values

This seems to be fixed.
### Request
``` 
{
    "type": "unique",
    "columns": [2]
} 
```

### Response
```
{
        "code": 4208,
        "message": "This column has non-unique values so a unique constraint cannot be set",
        "field": null,
        "detail": null
}
```
> Attempting to set a unique constraint with a supplied constraint name equal to that of an existing table

Here, the schema seems to be correct but the error message seems wrong.
### Request 
```
{
    "name": "Table 0",
    "type": "unique",
    "columns": [3]
}
```
### Response
```
{
        "code": 4205,
        "message": "Relation with the same name already exists",
        "field": null,
        "detail": null
}
```
> Non-existent column id

Gives a **500** error.

**Comment by kgodey** [comment]
@Anish9901 what is the status of this issue?

**Comment by Anish9901** [comment]
> @Anish9901 what is the status of this issue?

@kgodey this is the current status
## Solved: 
- Invalid "type", e.g.:

    ```json
    {"type":"foo","columns":[1]}
    ```

- An empty `columns` array, e.g.:

    ```json
    {"type":"unique","columns":[]}
    ```
## Unsolved:
- Attempting to set a unique constraint by supplying the id of a column that exists in a different table from the table whose id is supplied in the URL.

- Non-existent column id, e.g.:

    ```json
    {"type":"unique","columns":[9999]}
    ```

@silentninja told me to create a new issue regarding these https://github.com/centerofci/mathesar/pull/1406#issuecomment-1224325660 I forgot to do so, sorry about that.

**Comment by kgodey** [comment]
Okay, thanks! Please do go ahead and create the missing issue(s).

**Comment by kgodey** [comment]
Closing this, too old, requirements are likely out of date, we'll be updating our APIs soon anyway. We can create a new issue if we need this functionality in the future.
