### ISSUE TITLE
Slow Response Time in case of unhandled Exception

### ISSUE THREAD

**Issue by silentninja** [mathesar-foundation/mathesar#1052]
## Description

When an exception is raised on the backend and does not get captured on the backend, the error response takes a long time to be generated.

## Expected behavior
The Error Response should not take too long

## To Reproduce
1. Remove the catch block so that the exception is unhandled.  https://github.com/centerofci/mathesar/blob/5a6db9fa8e34bedd921304fe87f51d785a1e85ec/mathesar/api/viewsets/records.py#L69 
2. Use the front end
3. Open a table where at least one column has a NOT NULL constraint set
4. Click the `+` icon at the bottom left of the table to begin adding a new record.
5. Observe a request to `http://localhost:8000/api/v0/tables/24/records/` that 
6. Observe HTTP response code of 500.

## Additional context

Refer to #858 for more details

**Comment by kgodey** [comment]
Closing this, too old, requirements are likely out of date. We can create a new issue if we need this functionality in the future.
