### ISSUE TITLE
Extend functions API to allow for the mathesar namespace to add DBFunctions, like `column_id`

### ISSUE THREAD

**Issue by dmos62** [mathesar-foundation/mathesar#1077]
## Problem
The functions API lives in the db layer, and we want to use it by specifying columns via their Django IDs, which is a mathesar layer concept. To maintain separation between the db and mathesar (also referred to as "ui" recently) layers, we're not making the db layer aware of column IDs and instead we're having column ids replaced with column names in the mathesar layer, before passing the JSON on to the db layer.

That works for the moment, but now we have two routines parsing the function spec JSON, which makes the syntax difficult to extend and maintain, since to make a change we have to do it in two places.

## Proposed solution
Remove the preprocessing/rewriting step. Instead, add support for extending the set of `DBFunction`s used to parse the function spec JSON into an SA expression. That way the mathesar layer could add a `column_id` DBFunction that would materialize into a column name reference when converting to SA expression, and the db layer would stay unaware of Django IDs.

This might have other uses, in case we want to use DBFunctions from namespaces downstream of the db layer.

## Additional context
Initially discussed here: https://github.com/centerofci/mathesar/pull/1069#issuecomment-1041566376

The context was that we were discussing making a change to the parameter JSON syntax, and I pointed out that making changes is awkward now because of two separate parsers having to be updated. Above proposed solution would fix this.

**Comment by dmos62** [comment]
This is still desirable.

**Comment by kgodey** [comment]
Closing, doesn't seem relevant with upcoming refactor removing SA.
