### ISSUE TITLE
Assess database type infrastructure

### ISSUE THREAD

**Issue by mathemancer** [mathesar-foundation/mathesar#1085]
## Problem

As we near the end of the initial round of implementing database types, we should reassess our current setup and look for improvements.  Especially since some GSoC projects involve adding types or adding features to types.

## Proposed solution

We should make it as easy and obvious as possible to

- Add a new custom type
- Add support for native PostgreSQL types
- Add support for common 3rd-party types (e.g., PostGIS)
- add support for `type_options` for a type.

## Additional context

This is a draft while we figure out what improvements might actually be possible.

**Comment by seancolsen** [comment]
I'm closing this since it's too old and too vague.
