### ISSUE TITLE
Public functions should use attnums instead of column index or column name

### ISSUE THREAD

**Issue by silentninja** [mathesar-foundation/mathesar#1095]
## Problem
Currently, most public functions are using name or index to identify columns. This is brittle, and we've decided to change to using the attnum property of columns instead.

## Proposed solution
Each public function in the `db` module should use attnum instead of column_index, and should properly use the table_oid, attnum pair to identify columns for its logic.

## List of functions (WIP):
- db.constraints.operations.select.get_column_constraints

**Comment by vrutik2809** [comment]
@silentninja I would like to work on this issue.
Can you please elaborate on this?

**Comment by vrutik2809** [comment]
@silentninja any update on this?

**Comment by mathemancer** [comment]
@vrutik2809 The code base is split into `mathesar` and `db` modules. This issue is to check for any function which is accessed from outside the `db` module (by a process of the `mathesar` module) which uses column name or column index to access a column, enumerate those functions, and rewrite each one to use `attnum` instead.

@silentninja may have more details, but perhaps that can get you started.

**Comment by silentninja** [comment]
@vrutik2809 Sorry for the late reply, I missed the Github notification. 

I don't have much to add to @mathemancer's comment.

**Comment by vrutik2809** [comment]
Okay. So functions which are accessed through `db` module are using `attnum` to access column and functions which are accessed outside the `db` module may or may not use `attnum`. Hence, I need to go through all the functions which are accessing the column and need to refactor them to use `attnum`.

@mathemancer or @silentninja  correct me if I'm wrong.

**Comment by mathemancer** [comment]
I'm sorry, I don't quite understand your phrasing. Any function which is a part of the `db` module, but which is called from outside of the `db` module should use `attnum` as the argument that refers to a column. That should be converted to a column name or index at the last possible instant when the database itself is being accessed by the function internally. Does that help?

**Comment by vrutik2809** [comment]
Okay. I think I got it.
For example consider [this](https://github.com/centerofci/mathesar/blob/master/db/columns/operations/alter.py#L60) function which using `column_name` to access column which I need to change to `column_attnum`. Similarly for other functions right?

**Comment by mathemancer** [comment]
@vrutik2809 Precisely. Please feel free to submit PRs a bit at a time instead of trying to solve all the functions at once. Thank you!

**Comment by kgodey** [comment]
Closing, too old, requirements likely out of date.
