### ISSUE TITLE
Find a way to resolve conflicting currency symbols when inferring Money type display options

### ISSUE THREAD

**Issue by silentninja** [mathesar-foundation/mathesar#1219]
## Problem

Based on the imported data, we infer money types and their display options. The inference is based on the currency symbol, so "$500" would be inferred as `en_us` based on `$` symbol.

Certain currencies use the same symbol to represent their currency, for example: 
- "Canadian dollar" uses `$`
- "US dollar" uses `$`

So we might be inferring the wrong currency code. 

## Proposed solution
~Use locale information sent from the frontend and use it to resolve currency symbol conflicts during data import~

Set a default currency code for the conflicting currency symbols. In the case of `$`, the default will be `US dollars`

## Additional context
- Blocked by #1218 - It would be better to wait until #1218 is fixed, so that most of the duplicate currency codes can be eliminated

**Comment by mathemancer** [comment]
This makes a number of assumptions that I don't think are quite solid:
- U.S. citizens don't make spreadsheets with Canadian dollars.
- The locale where the CSV was exported is the same as the UI when the importing happens.
- The locale of the UI will be related to a given currency symbol at all (U.S. locale users can also have EUR in their spreadsheets).

**Comment by silentninja** [comment]
> The locale of the UI will be related to a given currency symbol at all (U.S. locale users can also have EUR in their spreadsheets).

The issue is for resolving conflicting currency symbols.

> U.S. citizens don't make spreadsheets with Canadian dollars.

While inferring, we are trying our best to get the correct currency symbol. If it turns out to be wrong, the user can change it anytime

> The locale where the CSV was exported is the same as the UI when the importing happens.

Should we be looking into the locale of the csv file rather than the UI? I think that makes more sense than the locale information of the user. 


@mathemancer Do you have any other ideas to resolve these conflicts?

**Comment by mathemancer** [comment]
> The issue is for resolving conflicting currency symbols.

I'm aware; I was just using EUR as a stand-in for the € symbol.

Why do we need a full locale? Is it just for commas and dots and so on? Or just the symbol? I'd avoid trying to infer a locale at all, and just use the international default. Anyone not in such a locale is probably used to needing to adjust a configuration.

If we really want to try, I'd start with any locale the user has set for other columns that fits, then fall back to the most common international locale that fits.

**Comment by silentninja** [comment]
> Why do we need a full locale?

Just to be clear, by locale I meant locale code, which can be fetched from the `Accept language` header.

> Is it just for commas and dots and so on? Or just the symbol?

There isn't any need for it as most of the conflicting currencies have the same display values, it is just their human-readable name and the resulting(perceived) fiat value of the currency will be different(CAD vs USD), which won't affect anything unless we have currency conversion in place.

>  I'd avoid trying to infer a locale at all, and just use the international default

This was my knee jerk solution and seems to be the obvious one too. Using locale seems like an unwanted gimmick, I think I will go with this solution. Conflicting currencies are very ad-hoc and would be best for the user to decide than us.

 I will change the issue description to use international defaults for conflicting currency symbols.

**Comment by seancolsen** [comment]
> Set a default currency code for the conflicting currency symbols. In the case of `$`, the default will be `US dollars`.

I could be mistaken or misunderstanding, but I think our implementation of Mathesar's Money ended up taking a turn somewhere along the way, perhaps after this ticket was written.

We don't seem to be storing any sort of "currency code" for money types. We store the currency _symbol_.

![image](https://github.com/mathesar-foundation/mathesar/assets/42411/1466d276-04d6-46ee-804e-da8b9b02187a)

As such, I'm reasonably confident that this ticket is now out of date and can be closed.

We can re-open if we have clear steps to reproduce a problem.
