### ISSUE TITLE
Increase Playwright timeout to 30s and re-enable flaky tests which are commented-out

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#1285]
The test `test_import_from_file` has been failing in some PRs. For example

- https://github.com/centerofci/mathesar/runs/6013686657?check_suite_focus=true
- https://github.com/centerofci/mathesar/runs/5999506321?check_suite_focus=true

In those logs you'll see:

> locator_assertions.to_be_visible with timeout 5000ms

Why is the timeout 5s and not 30s like we've set with our `page` fixture override? I've tried to troubleshoot this but had a hard time figuring it out. I can't reproduce it locally.

For the sake of allowing us to move forward with other code, I've commented out the `test_import_from_file` test. To close this ticket, we should diagnose the cause of the timeout not being set correctly and fix it to be 30000ms instead of 5000ms.

**Comment by seancolsen** [comment]
Same with `test_import_from_clipboard` now. I've commented out that one too. Same problem.

**Comment by seancolsen** [comment]
Same with `test_add_column`

**Comment by seancolsen** [comment]
I spent a good while troubleshooting this today and opened an upstream issue: https://github.com/microsoft/playwright/issues/14294 asking for more help.

**Comment by pavish** [comment]
We can also pass the timeout directly to the assertion method as per the docs. For the time being, we could do this instead of commenting out the tests.

https://playwright.dev/python/docs/next/test-assertions#locator-assertions-not-to-be-visible

**Comment by hitenvidhani** [comment]
Are all integration tests removed? As they are not visible in the tests directory. If yes, then we can close this issue.

**Comment by seancolsen** [comment]
Thanks for pointing this out, @hitenvidhani. Yes, we can close this now.
