### ISSUE TITLE
Be explicit when displaying empty strings as cell values

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#1373]
## Current behavior

- When a cell value is an empty string, the cell displays as empty.

    ![image](https://github.com/centerofci/mathesar/assets/42411/99bab495-be6c-4497-a6ef-7a80d69c82d0)

- Some users may not understand that an empty string is a distinct value from `NULL`, and the empty cell may lead them toward an incorrect assumption that the value of the cell is `NULL` (especially if no `NULL` cells are nearby for comparison's sake).

## Desired behavior

- When a cell value is an empty string, the cell displays `(empty string)` stylized in a manner distinct from regular cells.

    For example:

    ![image](https://github.com/centerofci/mathesar/assets/42411/57f1b84d-d0c5-4a31-824a-611cca29ab32)

**Comment by ghislaineguerin** [comment]
@seancolsen, could you please clarify if by displaying "<empty string>" you mean this text would be visible inside the cell whenever the value is an empty string?

**Comment by seancolsen** [comment]
@ghislaineguerin I edited the ticket description to add some clarity. Does the updated description answer your question?

**Comment by ghislaineguerin** [comment]
@seancolsen it does. Thanks! Would this affect types other than text?

**Comment by seancolsen** [comment]
@ghislaineguerin It would affect any type which permits an empty string to be stored as a value. Currently the "Text" appears looks to be the only type which would allow that value, but in theory there could be other types that we add in the future which also allow empty strings to be stored.

**Comment by seancolsen** [comment]
The maintainers team met today to review this issue and we decided not to pursue this.
