### ISSUE TITLE
Fix summary templates that refers to a deleted column

### ISSUE THREAD

**Issue by silentninja** [mathesar-foundation/mathesar#1461]
A sub task of #944 
## Description
When a column referred in a summary template is deleted, the summary template does not clear the column reference. This ends up with the summary template having an invalid reference.
## Expected behavior
If the summary template is `{1}-{2}` and the column with `id=1` is deleted, the template should be `-{2}`

**Comment by seancolsen** [comment]
This is fixed by our new record summary template design
