### ISSUE TITLE
Customize page favicons

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#1520]
## Current behavior

- All pages have the same favicon

## Desired behavior

- Our [Navigation Specs](https://github.com/centerofci/mathesar-wiki/blob/master/design/specs/navigation.md#navigation-via-page-url) require that we use distinct favicons for pages that represent different types of entities.

## Implementation

1. Review specs to see which entities require custom favicons.
1. Look in `src/icons.ts` to find the correct FontAwesome icons for those entities.
1. Generate custom favicons based on the FontAwesome icons. I like to follow [this guide](https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs) for favicons, but we could probably get away with just using the SVG. Which browser's don't support SVG favicons these days? It might be good to look.
1. Use `<svelte:head>` to modify the HTML `<head>` element from within components like `TablePage.svelte`

## See also

- #3605 which is simpler (just one static favicon) and higher priority

**Comment by seancolsen** [comment]
This will be visible in the demo video, so I'm bumping this up with the hope that it might be quick to implement.

**Comment by IyadElwy** [comment]
This should be easy enough. Should I go ahead and start working on it ?

**Comment by seancolsen** [comment]
Sure, @IyadElwy feel free to start work and submit a PR when you have one. Thanks!

**Comment by IyadElwy** [comment]
@seancolsen 
I wanted to ask about the favicon locations. Right now I've been able to only locate `logo.svg` in  `mathesar_ui/src/static-assets/logo.svg`, which is the mathesar logo. Are there any other local svg's or should I search a 3rd party provider like FontAwesome for the rest of the icons like for example the database page ?

I thought I'd ask first to adhere to any conventions.

**Comment by seancolsen** [comment]
@IyadElwy You'll need to look in our `src/icons.ts` to find the name of the FontAwesome icon that we're currently using to represent the entity. Then you'll need to go to the FontAwesome website and download that icon as an SVG. Then save those files alongside `mathesar_ui/src/static-assets/logo.svg`

**Comment by seancolsen** [comment]
And actually we have started using custom icons for some of the entities (e.g. Exploration). You'll need to create an SVG for that. The simplest way is to inspect the DOM when viewing a page with that icon and then copy the HTML that gets generated for it. You can use that same process for all the icons actually (including the FontAwesome ones).

**Comment by IyadElwy** [comment]
I got the favicons to appear like so:
![mathesar_tables _ public _ Mathesar - Google Chrome 11_20_2022 2_45_10 PM (2)](https://user-images.githubusercontent.com/83036619/202903889-2007238d-a2b5-4fed-b2d2-7a7d4426335d.png)
But I struggled to understand how to use the `icons.ts` file and I'm not sure if the implementation adheres to your style guides but I tried to do it in a modularised manner. 
I submitted a PR. If anything needs to be changed I'm always open to working on it again.

**Comment by seancolsen** [comment]
@IyadElwy I see you have a [`adding_favicons` branch](https://github.com/centerofci/mathesar/compare/master...IyadElwy:mathesar:adding_favicons) within your fork, but I don't see a PR open for this work. The next step here is to open a PR with those changes. Then we can discuss your implementation within that PR.

**Comment by kgodey** [comment]
@seancolsen the PR is #1958

**Comment by seancolsen** [comment]
Thanks, @kgodey. Not sure why I didn't see that before.

**Comment by seancolsen** [comment]
I no longer think this is worth doing, so I'm closing.
