### ISSUE TITLE
Change the data structure to store selections in the selection store

### ISSUE THREAD

**Issue by rajatvijay** [mathesar-foundation/mathesar#1732]
## Problem
The current structure is only capable to store the selected cells. 
`selectedCells: WritableSet<string>;`
This is not usable when the table has no rows hence no cells but the user should still be able to select columns and edit their properties as mentioned in #1684

## The rationale behind current implementation
The current implementation is based on the fact that when a cell is selected, a row and a column are also selected by default. Row selection can be described as selecting all the cells in a particular row. 
Column selection can be described as selecting all the cells in a particular column. 

## Proposed solution

@pavish [proposed](https://github.com/centerofci/mathesar/issues/1684#issuecomment-1256145741) the following design:

> The selection store to utilize a different structure instead of just the identifier string array, something like:
> 
> ```ts
> {
>    type: 'cell' | 'column' | 'row',
>    identifiers: string[],
> }
> ```
> 
> The identifiers here would depend on the type of selection.

**Comment by seancolsen** [comment]
I just merged #1733 which moves us forward with the "current implementation", but I do  think it's worth considering ways to improve this code.

Although I initially [expressed support](https://github.com/centerofci/mathesar/issues/1684#issuecomment-1256116844) for the current implementation, I think @pavish has a good idea (if I'm understanding it correctly). To flesh this idea out a bit more I'd propose the following:

In `src/stores/table-data/selection.ts`...

1. Rename the `Selection` class to `SelectionStore`.

1. Use the following:

    ```ts
    interface SelectionOfCells {
      basis: 'cells';
      cellIds: ImmutableSet<string>;
    }
    interface SelectionOfColumns {
      basis: 'columns';
      columnIds: ImmutableSet<number>;
    }

    type Selection = SelectionOfCells | SelectionOfColumns;

    class SelectionStore {
      // ...

      selection: Writable<Selection>;

      // ...
    }
    ```

This way, the selection is either a selection of cells or a selection of columns, but never both. The `SelectionOfColumns` type would only be used when the table is empty, similar to how we're currently doing it. I don't currently see a need for tracking a selection of rows, but if such a need arose in the future, we could modify the `Selection` type accordingly.
