### ISSUE TITLE
Improve `/constraints/` API performance

### ISSUE THREAD

**Issue by silentninja** [mathesar-foundation/mathesar#1764]
## Problem
`/tables/<id>/constraints/` takes around 2 seconds to respond

## Proposed solution
Performance can be improved by prefetching 
- Constrained column attnums in bulk
- Referent tables and referent column attnums in bulk

**Comment by silentninja** [comment]
@kgodey Should be in the Live Demo milestone?

**Comment by kgodey** [comment]
Moved to post-release improvements.

**Comment by kgodey** [comment]
Closing this, we can reassess performance improvements after upcoming backend architecture work is completed.
