### ISSUE TITLE
Have a section in table page to write queries

### ISSUE THREAD

**Issue by chidam333** [mathesar-foundation/mathesar#1822]
## Problem

No proper way to implement custom queries 
## Proposed solution

An addition of query option along with table column and row would be great

**Comment by kgodey** [comment]
@chidam333 could you provide some details about the kinds of queries you'd like to write using this feature?

**Comment by chidam333** [comment]
joins,update or any type of queries , something like what railway has .

**Comment by chidam333** [comment]
![image](https://user-images.githubusercontent.com/86545749/195653836-6973fde1-cd67-483b-abb6-7d3424011c99.png)

**Comment by seancolsen** [comment]
We'd like to implement something like this at some point, but we've decided to close this issue for the following reasons:

- This works is not a high enough priority for us to track in an issue right now.
- If/when we do decide to take up this work, it will requires significant product and UX design before we have something actionable enough to track within issues.
- We are considering larger changes to the table page and data explorer, and we'll need to flesh those out before we can move forward. We are taking the need for user-authored queries into consideration as part of those larger changes we are considering.
