### ISSUE TITLE
Pressing del should delete the selected row

### ISSUE THREAD

**Issue by chidam333** [mathesar-foundation/mathesar#1823]
## Problem
It is very intuitive to select a row and try to delete is using del key . Instead the user has to press the delete from record option . 
## Proposed solution

Making del as a cmd to delete row would be way better , a popup with a warning would reduce miss delete's .
We can also default to record menu when we select a row , it's table for everything now .

**Comment by seancolsen** [comment]
In #936 we also have a need to set a cell's value to `NULL` using a keyboard shortcut, and we've discussed using `delete` for that. We'll need to be sure to consider all these scenarios when designing this UX.

**Comment by chidam333** [comment]
Ah I see I am looking to solve #936 , I just noticed that even selecting a cell select's the whole row , I though earlier that clicking the left most column selects the row instead 😅 .

**Comment by seancolsen** [comment]
The maintainers team met today to discuss this issue. We would like to eventually give users the ability to delete rows via keyboard a shortcut. However, we are closing this issue for now.

Our keyboard shortcuts system is very primitive and not yet well suited for features like this. Before we can build out more keyboard shortcut features, we'd like to make sure the keyboard shortcuts are user-configurable and more discoverable. We need to make sure we are thinking about keyboard shortcuts as a whole before we start building out more of them. For example we may decide that a keyboard shortcut which deletes records is _available_, but not configured by default (so as to provide defaults with a low risk of data loss).
