### ISSUE TITLE
Formulate Postgres-coupling-related assumptions

### ISSUE THREAD

**Issue by dmos62** [mathesar-foundation/mathesar#1854]
We don't have an explicit agreement on just how coupled to Postgres we want to be (or are prepared to be). We've also been experiencing disagreements on the subject. For the sake of productivity, we should formulate these assumptions.

**Comment by kgodey** [comment]
@dmos62 Unassigned you for now because you're not actively working on this. You can assign it back to yourself when it becomes a priority.

**Comment by kgodey** [comment]
There doesn't appear to be a clear action item here, so I'm closing this issue. If we have a specific disagreement come up in the future, we'll handle it then.
