### ISSUE TITLE
Pass metadata to the DBQuery methods instead of assigning a Metadata during object instantiation   

### ISSUE THREAD

**Issue by silentninja** [mathesar-foundation/mathesar#1877]
## Problem
Based on the conversation from #1851 We are passing `metadata` during the instantiation of DBQuery, this makes `DBQuery` stateful and might cause bugs if the methods are called after mutations to the database objects as they would still be using the stale metadata 

## Proposed solution
Pass metadata to the individual functions instead, so the code calling the function would be able to control the metadata that should be used.

**Comment by kgodey** [comment]
Closing, too old, requirements likely out of date.
