### ISSUE TITLE
Improve error reporting for Deleted columns of a Query

### ISSUE THREAD

**Issue by silentninja** [mathesar-foundation/mathesar#1952]
## Problem

When we run a query which contains multiple Deleted Columns using the `/queries/run/` API, the backend throws an exception that only contains the first column. This doesn't seem to be a good UX.

## Proposed solution

We should return an array of all the deleted columns that are part of the query. 

## Additional context

[Comment in issue #1905](https://github.com/centerofci/mathesar/pull/1905#issuecomment-1318198363) explains the problem in brief

**Comment by kgodey** [comment]
@silentninja Please add _some_ details to this issue, it's not at all clear what this is about. Also "bug reporting" implies (to me) that it's an external user reporting a bug, whereas (I think) this issue refers to improving user recovery from errors when columns are deleted.

**Comment by kgodey** [comment]
Closing, too old, requirements likely out of date.
