### ISSUE TITLE
Date picker re-styling

### ISSUE THREAD

**Issue by rajatvijay** [mathesar-foundation/mathesar#2011]

**Comment by pavish** [comment]
I'm picking this up as I'm more familiar with the date picker.

**Comment by seancolsen** [comment]
Could this be a ticket to push to a later milestone for the sake of cutting scope? I think the date picker looks pretty good as-is.

**Comment by kgodey** [comment]
I'll defer to @pavish – if it's pretty quick, it seems like it's worth doing.

**Comment by pavish** [comment]
I think it should quick enough (a day's work max), although I'd like to de-prioritize this until after I complete users & permissions.

**Comment by kgodey** [comment]
Okay I've moved it to post-release improvements, I don't think it's a release blocker.

**Comment by kgodey** [comment]
Closing this, not enough detail to be useful.
