### ISSUE TITLE
Add Production Docker Services

### ISSUE THREAD

**Issue by silentninja** [mathesar-foundation/mathesar#2032]
## Problem
Our current Docker compose contains services meant only for development.  For example, the current docker service creates a DB container by default and mounts `node_modules`. They add a lot of overhead which is not necessary for production deployment.

## Proposed solution
Add Docker Services that do the following
- [ ] Docker Service to start only the Mathesar Backend and the frontend Server without starting the DB server.
- [ ] Docker Service to use the Production build
  - [ ] Tidy up build.
  - [ ] Avoid binding Docker folders to the local folders
  - [ ] turn off `dev` flags.
  - [ ] Avoid hot-loading files
  - [ ] Remove any development-related configurations
  - [ ] Replace our Django server with a production server like Gunicorn
  - [ ] Add a Reverse proxy like Caddy on top of the Gunicorn Server.

**Comment by kgodey** [comment]
For "avoid hot loading files", I'm assuming our GitHub release will include pre-built static files for the frontend, and we'll use those in the production Docker container.

**Comment by silentninja** [comment]
> For "avoid hot loading files", I'm assuming our GitHub release will include pre-built static files for the frontend, and we'll use those in the production Docker container.

@kgodey Our Github release won't be responsible for building the static files, #2040 would be responsible for that. This issue is just concerned with building static files during the build process and using it instead of starting a frontend HMR server

**Comment by kgodey** [comment]
Okay cool, sounds good.
