### ISSUE TITLE
Installation script for fetching credentials from the user and storing it

### ISSUE THREAD

**Issue by silentninja** [mathesar-foundation/mathesar#2042]
## Problem
Our current process for storing the credentials is through the `.env` file. A non technical user might not be comfortable tinkering with a `.env` file. So we need a UI to abstract away the process of storing the config data into the config file.

## Proposed solution
Modify our current `install.py` script to prompt the user for the credentials and store them in an appropriate place depending on the platform
- `.env` file for Docker
- AWS secrets manager for AWS

## Additional context
We aren't considering it for the initial release 
- As our first release userbase would be able to modify the `.env` file
- Each platform has different ways to handle the env file making the install script write only to the `env` file doesn't make it an attractive feature to work on for the first release.

**Comment by kgodey** [comment]
Closing this, too old, requirements out of date with current installation setup. We can open a new issue if we need this functionality in the future.
