### ISSUE TITLE
Design for Mathesar Version widget

### ISSUE THREAD

**Issue by silentninja** [mathesar-foundation/mathesar#2047]
## Problem
We need a Design for the Mathesar Version widget before #2044 can be implemented.

## Proposed Solution

For the initial release, the widget will be doing a very simple job
- Show the current version
- Show any upgrade available
- Show a loading Indicator, when the automatic upgrade is taking place.
- Success message when the upgrade is successful

## Requirements
We need a place in the Mathesar Admin Panel to show all of this.

> What information would we need to show?
- [x] Current Mathesar version 
- [x] Latest Version available for an upgrade if any. It should be a clickable button if an upgrade exists.

> What actions can the user take?
- [x] Click on the Upgrade button if an upgrade is available. Based on the available upgrade options(will be known by the frontend)
   - [x] If the automatic upgrade is possible.  Start the upgrade process to automatically upgrade the containers. A loading spinner should show up when the upgrade process is taking place
   - [x] Or redirect them to the appropriate upgrade documentation for that platform if an automatic upgrade is not possible.

> What error states can exist?
- [x] An upgrade can fail. An error message has to be shown in that case

> Loading states
- [x] Once the user clicks "install update", we should have some sort of prominent loading states that indicates to the user that the update is being performed. It should go away when the update is done.

**Comment by silentninja** [comment]
> @silentninja Can you please list the requirements for the design?
> 
> * What information would we need to show?
> * What actions can the user take?
> * What error states can exist?

I have updated the description to answer these questions.

**Comment by dmos62** [comment]
This looks good for what the version widget should look like eventually, but, for the first release, we won't be able to trigger or track an upgrade through the UI. That will be done manually through `git` and `docker-compose`. The most we should do in that regard, for the first release, is provide a link to documentation on upgrading.

**Comment by silentninja** [comment]
Continuing the conversation from [Figma](https://www.figma.com/file/xHb5oIqye3fnXtb2heRH34?node-id=4041:32446#338379258)

@silentninja Comment
> But in case of an error, there won't be suitable medium to show the error message.

> So we need to keep the request alive in order to show the error message if any. So the user should not close the tab.

@pavish Reply

>That's a bad design strategy. Keeping a request alive for more than 10s is not a good idea. I consider 10s as the extreme max.

> Can we make this async? Can you store the status & errors somewhere on the backend (in memory, or the db), and provide the status via API. I believe we would have a history/audit table to keep track of previously done upgrades, where we should be tracking all attempts with errors.

**Comment by silentninja** [comment]
> That's a bad design strategy. Keeping a request alive for more than 10s is not a good idea. I consider 10s as the extreme max.

Can we make this async? Can you store the status & errors somewhere on the backend (in memory, or the db), and provide the status via API. I believe we would have a history/audit table to keep track of previously done upgrades, where we should be tracking all attempts with errors.


Adding a DB would bring in a lot of unnecessary complexity. I am not sure if it is worth the time spent. 

Other upgrade tools, simply ignore any state or error management. They show a fake loading progress bar and refresh after n seconds. If the upgrade hasn't taken place, the user would be looking at the logs. I would suggest we go this way.

**Comment by dmos62** [comment]
@silentninja @pavish I was working on the [progress report endpoint yesterday](https://github.com/centerofci/mathesar/issues/2198). Here's the [PR](https://github.com/centerofci/mathesar-update-companion/pull/2). I think this is trivial.

**Comment by silentninja** [comment]
> I've not seen any of my regular reliable tools that do this, where I have to check logs to see if there's an error. I think we have to err on side of caution here, because a messed up upgrade without information being provided clearly would immediately make me lose confidence in the tool I'm using.

I stand corrected. I was looking at Wikijs and a bug-creating app update companion as an example. It didn't make sense for them as most of their upgrades succeed most of the time. But for our case, I think we need definitely need an error handler, but I don't think it should be blocking the first release though.

**Comment by dmos62** [comment]
> @silentninja @pavish I was working on the [progress report endpoint yesterday](https://github.com/centerofci/mathesar/issues/2198). Here's the draft [PR](https://github.com/centerofci/mathesar-update-companion/pull/2). I think this is trivial. I'll review above discussion and respond if I have input later in the day.

To further illustrate my proposal, I sketched what the responses would look like in this comment: https://github.com/centerofci/mathesar/issues/2198#issuecomment-1372490503

**Comment by mathemancer** [comment]
We're going to go a different way for notifying about versions.
