### ISSUE TITLE
Weird cell selection behavior when dragging from cell to header

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#2122]
In the video below, notice how the cell selection changes abruptly when dragging from cells to column/row headers.

https://user-images.githubusercontent.com/42411/208515064-5aec64fb-f0c4-4bdd-ac0f-0a7aae5dcf8b.mp4

I would expect it to work like this:

https://user-images.githubusercontent.com/42411/208515593-814c8448-9f00-4f99-89f1-a271f69388a8.mp4

**Comment by siddhart1o1** [comment]
I want to work on this issue. Please assign this to me.

**Comment by rajatvijay** [comment]
@siddhart1o1 sure, here you go.

**Comment by siddhart1o1** [comment]
@rajatvijay I have created a PR for this issue, please review.  
Thanks !
