### ISSUE TITLE
Unhandled error for exclusion constraint violation

### ISSUE THREAD

**Issue by mathemancer** [mathesar-foundation/mathesar#2126]
## Description

When there's a violation of an exclusion constraint, we show a python error in the front end (in the hover box thing).

## Expected behavior

We should handle this error better in the service layer to give the front end a nicer error to display.

## To Reproduce

Start with the library demo set. Add an exclusion constraint to the "Checkouts" table using 

```sql
CREATE EXTENSION IF NOT EXISTS btree_gist;
ALTER TABLE "Checkouts" DROP CONSTRAINT IF EXISTS sim_chck_excl;
ALTER TABLE "Checkouts"
  ADD CONSTRAINT sim_chck_excl
  EXCLUDE USING gist
    ("Item" WITH =, tsrange("Checkout Time", "Check In Time", '[]') WITH &&);
```

Go to the front end, try to add a checkout for a book that hasn't yet been checked in. See the bug.

## Additional context

It's worth considering whether we should wrap all such errors into some kind of "Unknown error occured" catch-all.

**Comment by kgodey** [comment]
Moving this to the Backlog – this isn't critical enough to block launch.

**Comment by SafeEHA** [comment]
Hello @dmos62, i see this issue hasn't been fixed yet, I would like to take it up

**Comment by rajatvijay** [comment]
@SafeEHA sure, go ahead. Submit a PR.

**Comment by manthan-jsharma** [comment]
@mathemancer , @rajatvijay , I noticed that no one is currently working on this issue. Can i pick this up ?

**Comment by dmos62** [comment]
@manthan-jsharma definitely!

**Comment by raisachatterjee** [comment]
Hi, 
Can i start working on this ?

**Comment by dmos62** [comment]
@raisachatterjee you've already been assigned to another issue and someone else has said that they'd like to work on this.

**Comment by imshivam-gupta** [comment]
Hi Everyone I am new to open source,
Is anyone currently working on it or I can try to address this and submit pr
