### ISSUE TITLE
Do not select columns when hovering column headers in a table with no rows

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#2130]
## Steps to reproduce

1. Open the Table Page for a table with no rows.
1. Hover the column headers (without clicking).
1. Expect no changes to the cell/column selection.
1. Observe that columns are selected as you hover.

https://user-images.githubusercontent.com/42411/208681963-f897e982-8514-418d-ab32-f22581dfb55e.mp4

CC @rajatvijay

**Comment by kgodey** [comment]
Moving to backlog; doesn't block launch.
