### ISSUE TITLE
Keep using `.volumes` for postgres data locally.

### ISSUE THREAD

**Issue by mathemancer** [mathesar-foundation/mathesar#2324]
## Problem

We've changed to using an internal docker volume instead of a directory mount for postgres data. This makes sense for production, but is cumbersome for some dev uses. In particular, I could easily maintain multiple states of Mathesar on my local machine by keeping multiple `volumes` directories, and switching `.volumes` using simlinking.

## Proposed solution

I think using `.volumes` for local development is easier and more flexible, and I'd like to go back to that approach.

## Additional context

An alternative solution I'd accept would be to:
- thoroughly document how to mange docker volumes. 
- Figure out how to either easily switch which volume goes with a container on the fly, or switch versions of containers in the `docker-compose` network on the fly.

**Comment by silentninja** [comment]
`.volumes` was a docker volume too. The only difference with our current setup is that the postgres volume directory has been moved to default docker volumes directory which can be found at `/var/lib/docker/volumes/` in case of **Linux.** So any of the previous workflow based on`.volumes` directory can still work if we replace `.volumes` with `/var/lib/docker/volumes/`

**Comment by silentninja** [comment]
> thoroughly document how to mange docker volumes.

There is a [docker extension](https://hub.docker.com/extensions/docker/volumes-backup-extension) which should help manage docker volumes with ease. The person documenting should consider adding it to the documentation as it is helpful for people looking for GUI solution.

**Comment by silentninja** [comment]
I am marking it as a draft as we haven't decided how to proceed.

**Comment by dmos62** [comment]
There's ways to copy/move things from/to Docker volumes. If there's a workflow that depends on being able to do that conveniently, I think making shell scripts for that makes sense.
