### ISSUE TITLE
Allow dragging to modify precedence of sorting conditions

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#2349]
## Context

On the Table Page, we have this UI to add/edit sorting conditions

![image](https://user-images.githubusercontent.com/42411/214369653-1b6680f8-d490-40a0-98cd-e39992fea544.png)

## Current behavior

- Modifying the precedence of sorting conditions requires the user to remove the conditions and re-add them.

- The column selection dropdown is only enabled within the last entry.

## Desired behavior

- Users can sort entries via dragging to modify their precedence. _(More details below.)_

- Column selection dropdowns in all entries are enabled. The array of _options_ within each column selection dropdown is reactively derived so as to include only the table columns which are not specified by any sorting conditions. (These changes are necessary to make the logic for each sorting entry independent of its index within all sorting entries.)

### Dragging behavior specifications

- There is a [grip](https://fontawesome.com/icons/grip?s=solid&f=classic) icon to the left of the column selection dropdown. Hovering the grip icon shows a `grab` cursor.

- Users can grab the grip via mouse or touch. Use [pointer events](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events).

- When grabbed:

    - Within the bounds of the sorting entries container, the sort entry moves vertically with the pointer. It does not move horizontally.

    - Other entries within the list slide as they are re-ordered. When sliding, their movement is animated and their z-index is such that they appear _under_ the entry being moved.

    - The sorting precedence is _not_ modified while dragging.

    - The pointer can move anywhere on the page while dragging. Use [pointer capture](https://developer.mozilla.org/en-US/docs/Web/API/Element/setPointerCapture) on the `body` for this.

    - The cursor shows as `dragging`.

- When released:

    - The precedence of sorting entries is modified.

    - A new request is sent to reload the table with the updated sorting. (This should happen automatically when modifying the sorting store)

- Ideally we would implement all of the above without any extra JS dependencies. If you are implementing this and can make a strong case for using a 3rd party library, then we'd be open to considering it before you begin implementation.

@kgodey @ghislaineguerin and @pavish I'd like your opinion on the UX changes I'm proposing here. I will un-draft this issue and apply a "help wanted" label if you all sign off.

@pavish If we implement this from scratch, I'd like to use [pointer events](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events) even though [browser support](https://caniuse.com/pointer) is still only at ~95%. Is that okay with you? It seems okay to me for this feature because it's a convenience feature, not a make-or-break feature. Users can still work around it in the rare case that their browser does not support pointer events.

**Comment by kgodey** [comment]
Yes, that's fine with me.

**Comment by pavish** [comment]
> I'd like your opinion on the UX changes I'm proposing here. I will un-draft this issue and apply a "help wanted" label if you all sign off.
> If we implement this from scratch, I'd like to use [pointer events](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events) even though [browser support](https://caniuse.com/pointer) is still only at ~95%. Is that okay with you? It seems okay to me for this feature because it's a convenience feature, not a make-or-break feature. Users can still work around it in the rare case that their browser does not support pointer events.

Yes, both of these are fine with me.

**Comment by dikwickley** [comment]
@seancolsen this looks interesting. I would like to work on this.

**Comment by seancolsen** [comment]
Sure @dikwickley go ahead. I think this would be a good issue for you. It's going to be significantly more complex than the ones you've done so far, but I think it may be within reach. If you get stuck, feel free to ask more questions here or in the front end channel on Matrix.

**Comment by dikwickley** [comment]
Hey @seancolsen I implemented a version of this. Here is the demo:

https://github.com/mathesar-foundation/mathesar/assets/31622972/4f3e6166-20b6-4eb6-8fbc-ba85bf28126c

If this looks good, I will clean up the code and submit a PR.

**Comment by seancolsen** [comment]
Wow @dikwickley! Fantastic work on this so far! Your video does an excellent job of demonstrating the exact behavior that I've specified, including important edge cases. Yes, please submit a PR with your work and mention me in a comment. I'll try to review it this week if I have time.
