### ISSUE TITLE
Navigate to linked table via cell context menu

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#2350]
## Current behavior

- We have this context menu on all cells.

    ![image](https://user-images.githubusercontent.com/42411/214412872-943385c0-e477-4498-8fe1-776dad604fce.png)

## Desired behavior

- When opened via a foreign key cell (as I've done in the above screenshot)...

    - (A) The "Go To Linked Record" functions the same, but is instead labeled as:

        > Open `Patricia Anderson`

        The icon is `iconRecord`

    - (B) The menu contains an additional entry labeled like this:

        > Open **Patrons** Table

        The icon is `iconTable`

- The (B) menu entry is also present when the context menu is opened via a foreign key column's header cell.

@kgodey Are these UX changes okay with you? If so, we can un-draft this ticket and mark it as "help wanted" and "good first issue".

**Comment by himanshuc3** [comment]
Heads up, Is this up for grabs @seancolsen ?

**Comment by kgodey** [comment]
Yes, it is. Assigned to you @himanshuc3

**Comment by himanshuc3** [comment]
Hey, a quick question @kgodey 
Given table above has foreign key containing names as values which might not be unique. 
So two records may have "John" as name and we still contain it's value in foreign key. I understand it is for better accessibility but how do we choose the column that may be suitable to substitute id with?

**Comment by kgodey** [comment]
@himanshuc3 you can set the Record Summary in the table inspector to something unique – you can include multiple columns if needed.

**Comment by hitenvidhani** [comment]
Hi @seancolsen 
The updated menu currently looks like this 
![image](https://github.com/mathesar-foundation/mathesar/assets/60215053/ff473bdc-fa67-4a50-86c9-cec8b0674f00)
(Contains necessary changes for this enhancement)

Where do we want the "Open Patrons Table"? I feel we should create a new Table menu like Row, Cell and Header.
