### ISSUE TITLE
Make column type inference per-column

### ISSUE THREAD

**Issue by dmos62** [mathesar-foundation/mathesar#2359]
Root issue: #2346

**Comment by dmos62** [comment]
Another reason to do this: a significant and/or accidental DDOS attack can be mounted by just going to an import view for a table and reloading it repeatedly. Even though a view has been closed/reloaded on the client, the backend will still be trying to finish the huge batch-inference responses (one for each view load) in the background.

**Comment by kgodey** [comment]
Closing, not enough detail to be useful, we can reopen if we prioritize this and have implementation specs.
