### ISSUE TITLE
Improve discoverability of sample data for new contributors

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#2384]
It occurred to me today that new contributors don't seem to have any way of easily discovering our library data set. I'd like to make it more discoverable, and I'm leaning towards the following:

1. Rewrite the main README on the [mathesar-data-playground](https://github.com/centerofci/mathesar-data-playground) repo as follows:
    - Cut most of the intro content, linking instead to the Mathesar repo
    - Add a section with clear, concise, imperative instructions for people who just want to load the sample data and move on to their next task with Mathesar. A newcomers should be able to go from landing on this README to having the latest recommended library data set loaded into their local Mathesar installation in under 5 minutes.
1. Add a "Sample Data" section to our [README](https://github.com/centerofci/mathesar/blob/master/README.md) (after "Local Development") linking to the `mathesar-data-playground` repo.
1. Add a "Get sample data" step within our [Contributor Guide](https://wiki.mathesar.org/en/community/contributing) (after "Get Mathesar running locally") linking to the `mathesar-data-playground` repo.

Does this seem okay @kgodey @mathemancer?

**Comment by kgodey** [comment]
That sounds fine as a documentation change, @seancolsen.

I think we should also figure out a quick path to loading the live demo data set into the main DB. This shouldn't be too hard because we already have logic for loading it into demo DBs in the `mathesar` codebase.  It will involve some code in addition to documentation changes, so it should probably be tackled as a future improvement.

**Comment by hitenvidhani** [comment]
Attaching the referred message which contains steps [here](https://matrix.to/#/!vXLxAqmrJWsDMWPSpo:matrix.mathesar.org/$fzmiXavtRwzg1d2eedG3MgeqOIgXAXZrwDe4SmCPphI?via=matrix.mathesar.org&via=matrix.org&via=t2bot.io)

**Comment by hitenvidhani** [comment]
Opened a PR to close this. 
https://github.com/mathesar-foundation/mathesar/pull/3535
