### ISSUE TITLE
Show readonly permissions in user edit page

### ISSUE THREAD

**Issue by pavish** [mathesar-foundation/mathesar#2556]
Split from https://github.com/centerofci/mathesar/issues/2432

Refer Permissions block in [Figma UX](https://www.figma.com/file/xHb5oIqye3fnXtb2heRH34/Styling?node-id=4608%3A32284&t=YuvUELJVDoSAdXfB-1)

**Comment by raunak-dev-edu** [comment]
Hello @pavish I would like to work upon this issue. Could you assign it to me

**Comment by kgodey** [comment]
Go ahead @raunak-dev-edu

**Comment by raunak-dev-edu** [comment]
Hey, @pavish, I Just wanted to confirm that I need to show all the tables in the permissions that a user can access or only the table with the viewer option, as you mentioned, show read-only permission. Does it mean to show a table with a viewer role in permission or to show all tables access in permission that can't be changed (read-only) in the edit user page?

I find in the Figma design that it shows all the access tables in the permission. Would you like me to do the same as this?
![Screenshot 2023-02-25 200020](https://user-images.githubusercontent.com/95216822/221362653-5d84d4b0-7c8e-40de-ad54-1c9655cde5e0.png)

**Comment by kgodey** [comment]
@raunak-dev-edu We should show all the permissions. "Read-only" in this case refers to the fact that the user cannot changes permissions from this page.

**Comment by raunak-dev-edu** [comment]
> @raunak-dev-edu We should show all the permissions. "Read-only" in this case refers to the fact that the user cannot change permissions from this page.

Alright Thanks for clearing my confusion @kgodey

**Comment by raunak-dev-edu** [comment]
hey, @kgodey , @pavish 
I am unable to get schema access to the user and respective permission. Is there any function or API available somewhere?
I haven't found it, so I am trying to make it, but that's not working. It's Showing undefined when I am trying to get the user schema role or even userId. I was trying to figure out what's the problem.
However, I am able to add warning message, i.e., 'Please navigate to the appropriate database or schema in order to grant
        access to the user.' the same as in the Figma design. 
You can see it here:-
![image](https://user-images.githubusercontent.com/95216822/223471283-d01aede4-47a8-4e1c-b584-43520624eb36.png)

**Comment by Anish9901** [comment]
@raunak-dev-edu You should be able to provide users with different roles using the "Manage Access" button on the database page just make sure you are logged in as an Admin though as only Admins can set user roles.
![Screenshot from 2023-03-07 23-04-05](https://user-images.githubusercontent.com/52523023/223504069-5d7e5240-c449-447a-9d9e-5d0f8fb82539.png)

**Comment by pavish** [comment]
@raunak-dev-edu Please refer [this documentation on how Users & Access levels work in Mathesar](https://docs.mathesar.org/product/users/).

You'll have to first create an user, then provide access to the user at the database level and schema levels as @Anish9901 pointed out above. Inside both the Database page and Schema page, you can notice the 'Manage Access' button which will open a configuration modal.

> I am unable to get schema access to the user

Once you've set the roles, you'll be able to obtain this information. You can refer the `UserModel` store which has `databaseRoles` and `schemaRoles` properties which will contain the information required.

**Comment by raunak-dev-edu** [comment]
Thanks, @Anish9901, @pavish, for this information. I have seen this, but I need some API like getSchemaAccessToUser and find getUsersWithAccessToSchema in UserModel that's been used in the 'manage access' button, like someway opposite to the used API. As we need to show schema, too, Do schemaRoles and databaseRoles properties also have schema name info? So that I can use this only and get the schema name along with the role.
Anyways I am trying this. I will let you know if I need any help.

**Comment by raunak-dev-edu** [comment]
Hey, @pavish @Anish9901 
I cannot fetch the database and schema name on the edit profile page. It's showing "undefined" all the way. I am trying to figure out the problem but cannot solve it. Could you help me out?
I have create a UserPermissionForm file for this issue please check this and let me know my mistake.

`<script lang="ts">
  import { Help } from '@mathesar-component-library';
  import WarningBox from '@mathesar/components/message-boxes/WarningBox.svelte';
  import type { UserModel } from '@mathesar/stores/users';
  import { getSchemasStoreForDB } from '@mathesar/stores/schemas';
  import { getUsersStoreFromContext } from '@mathesar/stores/users'; 
  import type { Database, SchemaEntry } from '@mathesar/AppTypes';

  export let database : Database;
  export let schema : SchemaEntry;
  export let userId: UserModel['id']
  const usersStore = getUsersStoreFromContext();
  $: user = usersStore?.getUserDetails(userId);
  export let userWithRole : UserModel['schemaRoles'];
  $: schemaStore = getSchemasStoreForDB(user?.databaseId);
</script>

<div class="user-permission-form">
  <div>
    <span>Permissions</span>
    <Help>User Permissions</Help>
  </div>
  {#if !userWithRole }
    <div class="user-without-permission">
      <WarningBox fullWidth>
        Please navigate to the appropriate database or schema in order to grant
        access to the user.
      </WarningBox>
    </div>
  {:else}
  <div>
    {database.name} / {schmema.name}
  </div>
  {/if}
</div>

<style lang="scss">
  .user-permission-form {
    display: flex;
    align-items: center;
    justify-content: center;
    margin-left: var(--size-large);
  }
  .user-without-permission {
    margin-left: var(--size-large);
  }
</style>
`

**Comment by seancolsen** [comment]
Unassigning due to inactivity

**Comment by seancolsen** [comment]
I think this is no longer relevant, given our new permissions functionality.
