### ISSUE TITLE
Upgrades for Deployment type 3

### ISSUE THREAD

**Issue by mathemancer** [mathesar-foundation/mathesar#2646]
## Problem

Deployment type 3 won't be possible to upgrade using our current upgrade infrastructure (i.e., watchtower, or some other upgrade-handling container).

## Proposed solution

We need a clear plan to encourage and help users who have installed with deployment type 3 upgrade their Mathesar installation. We should attempt to maintain parity with the upgrade functionality of the deployment types 1 and 2 upgrade container. Currently, this is only to upgrade our own python code, but this is likely to improve and expand very soon.

## Additional context

See #2427 for the details about the installation of this deployment type.

**Comment by pavish** [comment]
The documentation work for helping users upgrade such deployment types are covered by https://github.com/centerofci/mathesar/issues/2785.

This issue is for tracking one-click upgrades from the UI for non-docker-compose deployment types.
