### ISSUE TITLE
Type 1&2 upgrade container improvements

### ISSUE THREAD

**Issue by mathemancer** [mathesar-foundation/mathesar#2647]
## Problem

Currently, our only method for helping users upgrade their Deployment type 1 or 2 installations of Mathesar is to automatically download the `latest` image from Docker Hub and run it. This has some limitations:
- We can't let them upgrade to a specific version
- Any 'latest' version will automatically be targeted for upgrading, regardless of semantic version (e.g., if someone inadvertently pushes a build of an older version)
- This upgrade method doesn't allow for upgrading PostgreSQL features (e.g., types) unless the image does it on first run (a possibility)
- This upgrade method doesn't allow for upgrading the `.env` file or `docker-compose.yml`.

## Proposed solution

We should build a custom container that has more functionality. In this release, I think we should at least give the ability to upgrade to a specific semantic version. As a stretch, we should add functionality to upgrade the `.env` and `docker-compose.yml` files.

**Comment by kgodey** [comment]
Closing, I don't think building a custom upgrade container is a priority.
