### ISSUE TITLE
In Firefox, dragging to re-order columns is not possible from empty space in column header

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#2651]
## Steps to reproduce

1. Identify a column which is wide enough to have empty space in the column header to the right of the column name.
1. Click on the column header to select the column.
1. Drag to re-order the column by initiating the drag event over the column name text. Observe that the column can be dragged. Good.
1. Drag to re-order the column by initiating the drag event over the empty space to the right of the column name text. Expect that the column is dragged, as before. Instead, observe that nothing happens.

## Notes

- This issue originally surfaced in a [PR review](https://github.com/centerofci/mathesar/pull/2213#pullrequestreview-1262551150). Search the PR comments for `(9)` to see references to this problem within several comments.

- As @AlekLefebvre [mentioned](https://github.com/centerofci/mathesar/pull/2213#issuecomment-1458546855), this issue may be related to a [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=568313#c16).

**Comment by DanyaalMahmood** [comment]
Hey @seancolsen can I work on this?

**Comment by seancolsen** [comment]
Sure @DanyaalMahmood, go ahead

**Comment by Anish9901** [comment]
Unassigned due to inactivity.
