### ISSUE TITLE
Update all command in local development contribution guide to use the correct container

### ISSUE THREAD

**Issue by silentninja** [mathesar-foundation/mathesar#2693]
## Description
Our docker containers for local development have changed from `mathesar_service` to `mathesar_service_dev`. This isn't reflected in the [documentation](https://github.com/centerofci/mathesar/blob/develop/docs/docs/contributing/local-dev.md)

## Expected behavior
The commands mentioned in  [documentation](https://github.com/centerofci/mathesar/blob/develop/docs/docs/contributing/local-dev.md) should use the correct Mathesar development container

**Comment by Sukshan** [comment]
Can I work on this issue @silentninja

**Comment by pavish** [comment]
@Sukshan Sure, go ahead!

**Comment by pavish** [comment]
@Sukshan Sorry about the hasty assignment, it looks like there was a PR open for it already by @manavana-pierroldin.

Please look for other open issues.

**Comment by rajatvijay** [comment]
@manavana-pierroldin could you please comment on this issue, so that we can assign this to you? Thanks!

**Comment by manavana-pierroldin** [comment]
This issue is already taken
