### ISSUE TITLE
Modifying column properties leads to unwanted modification of column selection

### ISSUE THREAD

**Issue by Aritra8438** [mathesar-foundation/mathesar#2842]
## Description
When **property/data_type/default_value** of the focused column is changed, **primary_key column is getting focused.** 

## Expected behavior
Column focus should be conserved.

## To Reproduce
- Select a column.
- Restrict it to null/ Disallow null values/ or modify anything on **column inspector**.
- After successful modification, **Id column will automatically get selected**.

## Environment
 - OS: Ubuntu 22.10 (Kinetic Kudu)
 - Browser: Google Chrome
 - Browser Version: 112.0.5615.29

## Additional context

https://user-images.githubusercontent.com/64671908/234225491-469d91d4-547f-496b-a32a-7b8c892d6063.mp4

## Similar issues

- #1617
- #1686

**Comment by seancolsen** [comment]
Thanks for reporting this, @Aritra8438. I agree this needs to be addressed. Unfortunately the fix is not easy here. We have some lower-level refactoring that we need to do in order to make the front end reactive at a more granular level before we can handle this.

**Comment by seancolsen** [comment]
This is fixed now.
