### ISSUE TITLE
Reenable test parallelization via `pytest-xdist`

### ISSUE THREAD

**Issue by dmos62** [mathesar-foundation/mathesar#2843]
## Problem
We disabled test parallelization (we use `pytest-xdist` for that) by setting the maximum number of runners to 1. We did that because having multiple parallel test runners resulted in too many connections being opened to Postgres concurrently, which would cause fatal panics, which would cause false test failures. Test parallelization being disable is a nuisance, because it slows down developer workflow.

## Proposed solution
The "remove sqlalchemy" project aims to refactor mechanics that caused a surplus of connections. We expect connection use to become more economical as the project progresses, which should allow us to reenable test parallelization.

## Additional context
[There's been a concern](https://github.com/centerofci/mathesar/pull/2813#pullrequestreview-1384661653) that test parallelization could clash with how we currently define user databases. There's an issue tracking redoing how we define user databases: https://github.com/centerofci/mathesar/issues/2816. If the concern is deemed important, we could block this until #2816 is done.

## Status

- Blocked on removing SQLAlchemy

**Comment by seancolsen** [comment]
Still blocked

**Comment by mathemancer** [comment]
This isn't really going to be relevant moving forward.
