### ISSUE TITLE
Allow people to install Mathesar from source without NodeJS

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#2871]
## Current behavior

- Our docs [require](https://github.com/centerofci/mathesar/blob/develop/docs/docs/installation/build-from-source/index.md?plain=1#L8L11) NodeJS to install Mathesar from source.

- We don't actually need Node to _run_ Mathesar though.

- This installation requirement might present unnecessary friction for people wishing to install Mathesar.

## Desired behavior

- Our release process should include a build step to produces a tarball that people can download. Then they would be able to install Mathesar without NodeJS.

CC @pavish @silentninja

**Comment by silentninja** [comment]
I would prefer to add it to the v0.1.3 milestone.

**Comment by pavish** [comment]
@silentninja I'm adding this to Next release, but not specifically tying it to 0.1.3.

**Comment by silentninja** [comment]
>  I'm adding this to Next release, but not specifically tying it to 0.1.3.

@pavish I like the idea of using "Next release" tag. This is helpful to categorize issues better.
