### ISSUE TITLE
`Distinct list` results in raw date_time format when applied on `Datetime with timezone` columns.

### ISSUE THREAD

**Issue by Aritra8438** [mathesar-foundation/mathesar#2966]
## Description
If `Distinct List` transformation is applied on `Datetime with timezone` columns, it generates pills of raw datetime format.

By raw datetime format, I meant this format: `2023-06-08T06:30:00Z`.
We should calculate the time with timezone before rendering it. 

## Expected behavior
The format of the pills should adhere to the cell representaion of `Datetime with timezone` type in table.
That looks like: `06/22/2023 12:00`

# Screenshot

<img width="960" alt="image" src="https://github.com/centerofci/mathesar/assets/64671908/146e18ea-b560-45c9-93f8-2d491c2620a1">

**Comment by seancolsen** [comment]
Unassigning due to inactivity

**Comment by dikwickley** [comment]
@seancolsen This issue was still there so submitted a PR to fix this.
