### ISSUE TITLE
Add production configurations section to Docker installation document 

### ISSUE THREAD

**Issue by silentninja** [mathesar-foundation/mathesar#3122]
## Problem
The changes made to the Docker-based installation documentation in #3121 only contain the information for running the docker image on a local machine and does **not contain** information on the configuration details needed for setting up a production-ready Mathesar server.

## Proposed solution
Add a section to the documentation to include information on setting up a production server using the docker-based installation method.

**Comment by kgodey** [comment]
Closing, requirements out of date with new installation setup.
