### ISSUE TITLE
Appear on Supabase's integration website

### ISSUE THREAD

**Issue by dmos62** [mathesar-foundation/mathesar#3141]
The point of this issue is to make Supabase customers easily discover and install Mathesar (as well as ensuring that Mathesar works well with Supabase DBs and identifying any bugs).

## How

What are some of the ways we could integrate with Supabase? Motivation to do so includes increasing Mathesar's visibility and empowering users of both.

Here are a few Supabase links that might be interesting:
  - https://supabase.com/docs/guides/platform/marketplace
  - [https://supabase.com/partners/integrations#data platform](https://supabase.com/partners/integrations#data%20platform)
  - https://supabase.com/partners/integrations#become-a-partner
  - https://supabase.com/docs/guides/platform/oauth-apps/build-a-supabase-integration#create-an-oauth-app

There have been a few suggestions about this in a team meeting, but notes on them are scarce:
  - Someone noted that a new integration workflow is coming to Supabase,
  - Kriti noted that [Directus-Supabase](https://supabase.com/partners/integrations/directus) integration could be interesting to look at,
  - Mukesh recommended [Rowy](https://www.rowy.io/) as another example to explore.

**Comment by dmos62** [comment]
Hosted Supabase offers multiple ways to integrate. The most low-level way, and the most applicable to us, is directly connecting to a Supabase project's Postgres cluster. When you setup a Supabase project, and go into settings, you can find the postgresql connection string which you can use to connect to it via psql, or via Mathesar.

I've done that and I saw the schemas and tables pre-created by Supabase. I tried to import a medium-sized CSV file into a new table, but that broke Mathesar for me. I was getting 502s and saw log entries about timeouts. Seems to be a case of catastrophic performance problems.

Integrating with hosted Supabase might be as simple as integrating with any preexisting Postgres database. Hard to test definitely, due to the blocking performance issues I experienced when trying to setup a table with data.

**Comment by dmos62** [comment]
Closing, because I think the goals of the issue were reached. If there's disagreement on that front, this can be reopened and marked as blocked until relevant performance issues are resolved.

**Comment by seancolsen** [comment]
@dmos62 I'd like to suggest we re-open this. My understanding is that one of the primary goals of this ticket is to get Mathesar featured on this page: https://supabase.com/partners/integrations

Three companies who we [consider](https://wiki.mathesar.org/product/related/) to be competitors are already listed there: Directus, Appsmith, Retool.

Further, for some partners, Supabase appears to offer a more structured form of integration where you can click an "Add integration" button. I would be curious to see if that would be possible/appropriate for Mathesar.

![image](https://github.com/centerofci/mathesar/assets/42411/5f12f6e9-985e-4f7e-ab58-394b52fc902b)

**Comment by dmos62** [comment]
Another note, Supabase uses Postgres 15.

**Comment by dmos62** [comment]
@seancolsen notice that this ticket is about investigating the integration, not to become listed on their website. We could create another issue for that.

**Comment by kgodey** [comment]
I agree with @seancolsen, reopening. The point of this issue is to make Supabase customers easily discover and install Mathesar (as well as ensuring that Mathesar works well with Supabase DBs and identifying any bugs).

**Comment by dmos62** [comment]
I think creating a dedicated issue would have been simpler, but ok. I'll rename the issue and put @kgodey's specified goal in the description.

**Comment by kgodey** [comment]
This issue mostly involves research and developing requirements. Since it's not related to Mathesar code, I've moved it to Basecamp [here](https://3.basecamp.com/5718119/buckets/35541985/todos/6866424281).
