### ISSUE TITLE
Remove guided installation section

### ISSUE THREAD

**Issue by silentninja** [mathesar-foundation/mathesar#3167]
Based on our [installation plan](https://wiki.mathesar.org/en/projects/installation-improvements-plan-0_1_4), we won't be using the guided script anymore as a recommended installation method. 

- [Guided script page contents](https://docs.mathesar.org/installation/guided-install/) has to be removed from the installation documentation 
- The [Guided script page contents](https://docs.mathesar.org/installation/guided-install/) should point to [deprecated docker-compose](https://docs.mathesar.org/installation/docker-compose/) administration commands for users who are already installed Mathesar using the guided install

**Additional Context**

Blocked by #3166

**Comment by seancolsen** [comment]
@Anish9901 I've assigned this to you so that you have all the documentation work within the v0.1.4 milestone.

**Comment by seancolsen** [comment]
Addressed in #3227
