### ISSUE TITLE
Update Constraints for Positive Integers in `oid` and `column_order`

### ISSUE THREAD

**Issue by varshadr** [mathesar-foundation/mathesar#3176]
Currently, there is an issue with the constraints defined for the `oid` field in the Constraint object and the `column_order` field in the TableSettings object. Both of these fields have constraints that allow negative integers. 
For the `Objectid`(oid) field in the Constraint object, it is important to ensure that the identifier remains a positive integer. Similarly, the `column_order` field in the TableSettings object, which specifies the order of columns, should only accept positive integers.

**Comment by seancolsen** [comment]
I put this in the v0.1.4 milestone because we'd like to [Clean up django migrations before 0.1.4 release](https://github.com/mathesar-foundation/mathesar/issues/3296) and this PR associated with this issue introduces migrations (so we want to merge it before we clean up the migrations).
