### ISSUE TITLE
Documenting the requirement for superuser or owner privileges

### ISSUE THREAD

**Issue by silentninja** [mathesar-foundation/mathesar#3178]
## Problem
We need the user of the user database to be a  `SUPERUSER` or the `OWNER` of the database. But these permissions are very broad and not restrictive which a lot of users anxious. We need to convey the reason we need these requirements.

## Proposed solution
We need to figure out where to add this information.

## Additional context
More details are  in [this comment](https://github.com/centerofci/mathesar/pull/3117#issuecomment-1673834000)

**Comment by Anish9901** [comment]
Related to #3179
