### ISSUE TITLE
Do we need powerful privileges like superuser/owner for functioning of Mathesar?

### ISSUE THREAD

**Issue by silentninja** [mathesar-foundation/mathesar#3179]
## Problem
As of now we need the user of the user database to be a SUPERUSER or the OWNER of the database. A lot of users are not comfortable giving Mathesar these unrestrictive privileges. More discussions can be found [this issue](https://github.com/centerofci/mathesar/pull/3117#issuecomment-1673834000)

## Proposed solution
We need to have a product level discussion
1. Can reduce the required permissions without affecting the functionality of Mathesar?
2. How to downgrade the available features in Mathesar based on the giving permissions

**Comment by silentninja** [comment]
@mathemancer @pavish Tagging you since you are looking at researching Mathesar's permission in this cycle.

**Comment by Anish9901** [comment]
We only need a user to have `create` and `connect` privileges on a db to use mathesar.
