### ISSUE TITLE
Store installation metadata accessible by Mathesar during runtime

### ISSUE THREAD

**Issue by silentninja** [mathesar-foundation/mathesar#3180]
## Problem
Mathesar does not have any information on how it is installed which makes it hard to show customised information based on the installation method inside the app.

 For example, in-app updates are supported only for Docker image-based installation. We should be pointing the user to the respective update documentation for non-Docker based install but it is currently not possible as we don't have installation metadata

## Proposed solution
Since most of the installation is pre-built packages, we can add a metadata file which gets added to the package during build. Mathesar should read this metadata file to know about the installation information.

**Comment by kgodey** [comment]
Closing, requirements likely out of date with new installation setup.
