### ISSUE TITLE
Simplified User Flow for Listing and Adding Database Connections

### ISSUE THREAD

**Issue by ghislaineguerin** [mathesar-foundation/mathesar#3244]
## Description
The current user flow described in #3223 introduces navigation patterns that could lead to user confusion and make the process of adding new DB connections more cumbersome than it needs to be. 

To illustrate, consider the inconsistencies in navigation and functionality between Schemas and Databases:

For Schemas:

- Items in the list of schemas lead to the schema page and its corresponding tables.
- New schemas can be added directly from the schema page, and their details can be edited there as well.

For Databases:

- The list of databases serves solely as a navigational component and doesn't lead to a database-specific page.
- New database connections are added in a different section of the app, rather than directly from the databases page.

## Expected behavior

We aim to create a design that aligns closely with the information architecture and navigation structure found on the Schema page. For the sake of consistency and ease-of-use, we want to ensure navigation patterns remain predictable across the app.

To achieve this, we propose:

- Adding a new page tier above the existing lists of databases and schemas. This new page will display database connections and allow for their configuration.
- Enabling the addition of new database connections right from this new page, eliminating the need for additional navigation. The current plan is to implement an inline form similar to what's used in 'Constraints Settings'.

**Comment by seancolsen** [comment]
I'm closing because, as far as I can tell, most of this is already done or will be addressed in #3287.

Please feel free to re-open if I missed something.
