### ISSUE TITLE
Color palette doesn't work well with certain display settings 

### ISSUE THREAD

**Issue by Anish9901** [mathesar-foundation/mathesar#3248]
## Description

<img src="https://github.com/centerofci/mathesar/assets/52523023/36ac4f74-db58-4231-b11f-154722a54ee4" width=47%>
<img src="https://github.com/centerofci/mathesar/assets/52523023/29679f82-e782-42f6-a26f-9948a0325c34" width=50%>

Notice the color of the highlighted column type and that of the side panel in both the images, the first image is taken while using the monitor's default setting and the issue is caused specifically by the setting described in this [article](https://techglimpse.com/change-hdmi-black-level-in-samsung-monitor/).

## Expected behavior
Ideally we should choose a color palette that is agnostic of these settings.

**Comment by yagyesh-bobde** [comment]
I want to contribute to this issue. Can u tell me how do I get started?

**Comment by Anish9901** [comment]
@yagyesh-bobde This issue is restricted to design team and isn't open for outside contributors to work on, please look through other issues that interest you.

**Comment by yagyesh-bobde** [comment]
Alright thanks :)

**Comment by seancolsen** [comment]
We discussed this during today's product approval meeting and determined that it would not be sufficiently straightforward to make progress on this issue, so we decided to close it.
