### ISSUE TITLE
docs: there is no need to be root when using Docker Compose

### ISSUE THREAD

**Issue by frafra** [mathesar-foundation/mathesar#3277]
## Problem
Documentation uses `sudo` to set up Mathesar using Docker compose. There is no need to be root to run `docker compose` or to run Mathesar.

## Proposed solution
Avoid using `/etc` (leave to the user keeping the conf file there). Just use `wget`/`mv`/`docker compose` without `sudo`.

**Comment by mathemancer** [comment]
@frafra What's your OS?  Assuming you're on Linux, you'd typically need to add your user to the docker group to avoid `sudo`, which is a security issue. I suppose you could use the rootless mode from https://docs.docker.com/engine/security/rootless/ , but that comes with a number of limitations, and we had issues getting Mathesar's volume mounts working for a user who tried that in the past.

**Comment by mathemancer** [comment]
We're changing our docker compose setup to be less opinionated. While we'll still recommend using `sudo` for security and feature reasons related to the non-root docker solutions, the user can more easily avoid using it with the new setup.

**Comment by frafra** [comment]
> @frafra What's your OS? Assuming you're on Linux, you'd typically need to add your user to the docker group to avoid `sudo`, which is a security issue. I suppose you could use the rootless mode from https://docs.docker.com/engine/security/rootless/ , but that comes with a number of limitations, and we had issues getting Mathesar's volume mounts working for a user who tried that in the past.

Ubuntu, Docker rootless. Permissioning issues can arise when trying to delete bind mounts created by non-root users within the containers, for example. This can be solved by prepending `rootlesskit` to the command.

**Comment by mathemancer** [comment]
@frafra Update: I think the new version of the docker compose setup and associated docs have no need to recommend whether to use `sudo` or not. I.e., we simply won't give an opinion on it at all.
