### ISSUE TITLE
Implement the "Add Record" page

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#3285]
## Current behavior

- Adding new records is only possible from within the table page or the record selector.
- Data entry on mobile devices is especially difficult because the fields are presented horizontally instead of vertically.

## Desired behavior

- An "Add Record" page exists to make data entry easier in some cases.
- The page loads a blank form which looks like the top part of our existing "Record Page".
- Below the form there are the following buttons:
    - At the right, a "Reset" button which clears the form.
    - At the left:
        - a "Save and View" button which saves the form and navigates the the corresponding Record Page
        - a "Save and Add Another" button which saves the form an reloads a new blank form

- After clicking "Save and Add Another", a section appears at the bottom of the page (below the save buttons) which displays the recently added records. Each record is displayed as a record summary pill hyperlink, allowing the user to open a recently added record in a new tab. The most recently added record appears at the top of the list. Above list is a heading, reading "Recently Added Records". The list does not persist after navigating away from the "Add Record" page.

## Design work

- How does the user navigate to the "Add Record" page?

_Note: The "Add Record" page itself should be straightforward enough that it should **not** require any design work._

**Comment by nullHawk** [comment]
@seancolsen  I want to work on this issue.

**Comment by pavish** [comment]
@nullHawk This issue is not eligible for community contribution. Please see our [Contributor Guide](https://github.com/centerofci/mathesar/blob/develop/CONTRIBUTING.md) which states:

> ❌ Issues are not appropriate if they meet any of the following criteria:
>
>  - already assigned to someone
>  - labeled with a `restricted: ...` label
>  - labeled with any `status: ...` label other than `status: ready`

**Comment by nullHawk** [comment]
got it, Thanks

**Comment by seancolsen** [comment]
Duplicate of #2984
