### ISSUE TITLE
Make navigation header behave more consistently

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#3287]
### Good

I like how the navigation header has these "selectors". This is an example of a **good** page because it has selectors everywhere in the breadcrumb that it possibly can:

![image](https://github.com/centerofci/mathesar/assets/42411/a1e53b2b-0f57-4ef9-adda-733b255d7d78)

### Bad

But some of our pages _omit_ breadcrumb selectors where they could otherwise be included. For example:

![image](https://github.com/centerofci/mathesar/assets/42411/39369cb4-8f7f-408c-be3c-d702e154ac1a)

![image](https://github.com/centerofci/mathesar/assets/42411/91b79b1d-3331-4b50-a33d-3fd94c11d16a)

![image](https://github.com/centerofci/mathesar/assets/42411/24dafa2d-fdef-4ffe-8389-4121cf08514b)

![image](https://github.com/centerofci/mathesar/assets/42411/8bc9e79c-4ac0-4897-b773-aafcbe198ea1)

From a usability perspective I find this behavior to be **really frustrating** because I want to _rely_ on the breadcrumb for navigation. If it doesn't work everywhere that it should work, then I can't _rely_ on it, so I don't build my behavior around it. Our current design steers me away from using the selector feature &mdash; even on pages _where it exists_ &mdash; simply because I end up developing other habits.

## Proposed solution

The breadcrumb selectors should be present wherever possible.

Specifically, the selectors should be present in the red circles within my screenshots above.

See spec:
[Navigation Consistency Updates](https://wiki.mathesar.org/design/specs/navigation-consistency-updates/)

## Additional context

When we implemented the breadcrumb navigation, I made a case for using exactly the behavior I'm now proposing. However @pavish and @ghislaineguerin wanted the breadcrumb to be simpler so we ended up omitted the selectors in some cases.

Now that I've been using Mathesar more, I want to revisit our design and advocate more strongly for including the selectors everywhere. For me, **the selectors make Mathesar easier to use** so I would like to use them wherever we can.

## Related

- #3899
- #4048

**Comment by zaidmstrr** [comment]
can i work on it.

**Comment by seancolsen** [comment]
@zaidmstrr This issue is not eligible for community contribution. Please see our [Contributor Guide](https://github.com/centerofci/mathesar/blob/develop/CONTRIBUTING.md) which states:

> ❌ Issues are not appropriate if they meet any of the following criteria:
>
>  - already assigned to someone
>  - labeled with a `restricted: ...` label
>  - labeled with any `status: ...` label other than `status: ready`

**Comment by seancolsen** [comment]
We discussed this during today's product approval meeting. Everyone agrees that we should move forward with this.

This ticket requires the following UX work before we can move forward:

- Specify how the content within the dropdowns will incorporate links to "Import", and "Data Explorer".

    _Note: Be sure to specify that those links are rendered in an active state when on those pages, just as we do for schemas and tables_

**Comment by pavish** [comment]
I would like to add a point I mentioned in the meeting, which the UX work needs to account for.

* Make sure we differentiate the current active page in the breadcrumb.
  - Since the proposed solution adds an arrow mark dropdown at the end, we need to make it extra clear that the current open page is not within the last item, but _is_ the last item..
  - For eg., The breadcrumb would show: `Mathesar > mathesar_tables > Library >` when in the Library schema. We need to differentiate the color of `Library` in the breadcrumb to denote that it is the current active page.

**Comment by seancolsen** [comment]
Ghislaine and I discussed this in a [call](https://tldv.io/app/meetings/6756f0de62a36e00136ec11a) on 2024-12-09.

- We agreed that we'd also like to remove the Shortcuts menu (and I have #4048) to track that explicitly.
- We agreed that, for the sake of simplicity and implementation time, we will _not_ attempt to move the "shortcuts" items into the breadcrumb separator dropdown menus.
