### ISSUE TITLE
Implement new "connections" model and API

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#3291]
## Current behavior

We have a "databases" API which has developed some cruft and does not suit our changes in direction for v0.1.4.

## Desired behavior

We should have a new "connections" API which behaves as follows

- Use the endpoint `/api/db/v0/connections/`
- Have a "nickname" field that can be changed. Nicknames must be unique across all connections within one Mathesar installation.
- Not have `deleted` or `editable` fields, as in the current "databases" API.
- Write and read connections _only_ to and from the internal (Django) database. (This is in contrast to the old databases API which considered the environment variables to be a second source of truth for user database connections.)

**Comment by mathemancer** [comment]
Getting into implementing this.

@seancolsen I suggest making the following change as well:  Changing the field `db_name` to simply `database` . 

- `db_name` is the cause of a bunch of confusion in the back end.
- `database` is how the property of a connection is referred to in postgres (and other documentation).
- I'd want to go this direction anyway in the long run, may as well do it now if it's not a huge problem.

Normally, I'd just go for it, but I think this implies some front end work, and I know we're trying to get this done quickly.

**Comment by seancolsen** [comment]
@mathemancer `database` sounds fine to me. Go for it.
