### ISSUE TITLE
Front end work to re-organize DB connections

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#3297]
Per the [DB Connections Page Specs](https://wiki.mathesar.org/design/specs/connections-page/), we need the following changes.

## Database page

- Remove this sidebar

    ![image](https://github.com/centerofci/mathesar/assets/42411/0f603ca2-e2f8-4609-995e-2c7e7e22d6a4)

## Connections page

- Modify route
    - Old: `/administration/db-connection/`
    - New: `/connections/`

- Ensure the header navigation breadcrumb includes: the elephant and name, then the database switcher dropdown, then a "Connections" breadcrumb entry with the [plug](https://fontawesome.com/icons/plug?f=classic&s=solid) icon.

- Implement new page content design ([Figma](https://www.figma.com/file/xHb5oIqye3fnXtb2heRH34/Styling?type=design&node-id=6423-3425&mode=design&t=6oHGsZBIh0abNt5X-0))

    ![image](https://github.com/centerofci/mathesar/assets/42411/999b0d28-e88f-4357-b423-18a9b005f936)

- Leave an empty placeholder modal for the "New Database Connection" form, as to be implemented in #3311.

- Re-organize components to better suit the new location of this page

- Navigation

    - Add "Manage Connections" link within the database switcher dropdown

        ![image](https://github.com/centerofci/mathesar/assets/42411/a14ac7b9-9826-43ce-a43c-de97f0e2d789)

    - Add "Database Connections" link within the top right menu

        ![image](https://github.com/centerofci/mathesar/assets/42411/ba59e208-573c-4acc-9ada-9a017e10c458)

    - Remove "Database Connection" section from Administration navigation

        ![image](https://github.com/centerofci/mathesar/assets/42411/c29bade0-6f7e-429b-8fb8-0c897e398d12)

## Root route

- Modify redirection logic
    - Old: redirect to the database page for the connection with the highest id
    - New: If there is one and only one connection, then redirect to the database page for that connection. Otherwise, redirect to `/connections/`

## Navigation header

- Simplify the elephant logo and "Mathesar" text alongside it.

    - Currently, it's a hyperlink with a dynamic href depending on the current page. For any pages within a database connection, it points to the database page, and for other pages it points to the root route.
    - Instead, it should _always_ point directly to the root route. (No more dynamic behavior.) The navigation behavior when clicking it will then be subject to the redirection logic described above.

---

> **Note**
>
> This ticket is labeled "frontend" because the majority of the changes here are strictly frontend changes. However it will also require a tiny bit of backend changes for the page routing adjustments.

**Comment by rajesh604** [comment]
hello can you give me a reply on issue #3289

**Comment by dikwickley** [comment]
Hello @seancolsen I would like to work on this issue. Can you please assign it to me.

**Comment by seancolsen** [comment]
No @dikwickley, this issue is already assigned.

**Comment by pavish** [comment]
The route modification:
```
- Modify route
    - Old: `/db/<connection_name>/`
    - New: `/db/<connection_id>/`
```
is spun into a new issue: https://github.com/mathesar-foundation/mathesar/issues/3328
