### ISSUE TITLE
Disable selecting (and copying) table name during table deletion confirmation

### ISSUE THREAD

**Issue by dikwickley** [mathesar-foundation/mathesar#3307]
## Problem

When deleting a table we have to write the table name in a text input to confirm deleting that table.
Currently, users can just select the table name and copy paste that in the text input.
Many websites having similar flow (eg vercel or github) disable selecting the name and also prevent pasting inside the text input.
![image](https://github.com/centerofci/mathesar/assets/31622972/29f3546b-99c0-4b39-97e4-34a19d28265c)

## Proposed solution

Prevent selecting the text inside the delete modal. Also disable pasting into the text input box.

**Comment by seancolsen** [comment]
@dikwickley thanks for this suggestion.

I've labeled this ticket as `status: draft` for now though, indicating that it is not ready for implementation. I'm not sure we'll have agreement within our design team about whether or not we'd like to implement this. Our design team will take a look at update this ticket when we've made a decision. If we decide to move forward, we'll label this ticket with `status: ready`. If we decide this is not something we'd like to do, then we'll close this ticket.

**Comment by shivansh-bhatnagar18** [comment]
Yeah, I agree with @Tweniee and @dikwickley on this that many organizations (such as GitHub itself) have implemented this functionality of not letting the user copy the repository name while deleting it which verifies that the user is in his full senses and additional security from mishaps

**Comment by seancolsen** [comment]
We discussed this during today's product approval meeting and decided not to pursue this feature.
