### ISSUE TITLE
Linked record removal not being reflected after save

### ISSUE THREAD

**Issue by ghislaineguerin** [mathesar-foundation/mathesar#3308]
## Description
When attempting to remove a linked record from the the record page it does not get removed as expected. Despite saving changes, the linked record reappears as if it had not been deleted.

## Expected behavior
The deleted record should not reappear after saving changes.

## To Reproduce
Remove a linked record from the record page view:
<img width="789" alt="image" src="https://github.com/centerofci/mathesar/assets/845767/0e1b1408-6706-4092-b34c-beb9401f3394">
Save the changes:
<img width="775" alt="image" src="https://github.com/centerofci/mathesar/assets/845767/19ad0167-bd09-4136-aee7-4e5820f63eae">
Record is still there:
<img width="788" alt="image" src="https://github.com/centerofci/mathesar/assets/845767/82b6c832-42bb-4eca-8288-ce669f9b06b8">

**Comment by seancolsen** [comment]
I'm able to reproduce this. It appears to be isolated to the front end. The request body that the front end sends to `/api/db/v0/tables/<table_id>/records/<record_id>/` should contain an entry for the FK column. But instead the request body does not contain any entry for that column.

**Comment by dikwickley** [comment]
I would like to work on this. Please assign it to me.

**Comment by seancolsen** [comment]
Sure @dikwickley, go ahead.

**Comment by ajaySahani7945** [comment]
I would like to work on this problem, can you assign me this problem.

**Comment by seancolsen** [comment]
No @ajaySahani7945 this issue is closed
