### ISSUE TITLE
Front end changes for the "New Database Connection" form

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#3311]
See these [specs](https://wiki.mathesar.org/design/specs/new-db-connection-form/).

| Case A | Case B | Case C |
| -- | -- | -- |
| ![](https://wiki.mathesar.org/assets/design/specs/new-db-connection-form/a.png) | ![](https://wiki.mathesar.org/assets/design/specs/new-db-connection-form/b.png) | ![](https://wiki.mathesar.org/assets/design/specs/new-db-connection-form/c.png) |

**Comment by seancolsen** [comment]
I have a small design question about this feature. Not sure of the best place to ask, so I'm starting here. @ghislaineguerin @pavish @kgodey @mathemancer I'm tagging you to see if you want to weigh in with your opinion.

After a user adds a new connection, what should happen next?

- (A) close the modal, showing the table of all connections.

    We follow this pattern when creating new schemas. It would be the easiest to implement.

    This is potentially annoying if there are already lots of connections though. It's not necessarily easy to find the one you just added. 

- (B) same as (A), but also _highlight the new connection_.

    We don't think we follow this pattern anywhere.

    We could highlight the new one, but doing this well would be slightly complex (I can explain more if needed). This would be the hardest to implement of all the options.

- (C) navigate to the Database Page for the connection

    We follow this pattern when creating new tables because we navigate to the table.
    
    This is probably what most users would want, and it would be very easy to implement.

    I'm leaning towards this.

- (D) give the user a choice

    We don't follow this pattern anywhere, but for the [Add Record page (yet to be implemented)](https://github.com/mathesar-foundation/mathesar/issues/3285) it's important to me that we _do_ establish a pattern like this.
    
    Here's an example of what this could look like for the New Connection modal:
    
    <img src="https://github.com/mathesar-foundation/mathesar/assets/42411/1a86878b-d06c-4072-a2f9-503c760892ee" width="400px" />

    In the footer, we'd have this select input which would default to "Open", meaning that Mathesar would navigate to the Database Page for that connection. I like this pattern because I think it gives users a clearer expectation of the next step and it allows them to quickly add several connections in sequence.

    This would be relatively easy to implement.

**Comment by ghislaineguerin** [comment]
@seancolsen I'm also leaning towards option C. I think option D makes sense for the "Add Record Page" but not sure if needed for connections, since adding multiple seems unlikely.

**Comment by seancolsen** [comment]
Sounds good, @ghislaineguerin. I'll go with that unless anyone else wants to voice other opinions.

**Comment by pavish** [comment]
I also think C is the best option.

**Comment by kgodey** [comment]
+1 to option C.
