### ISSUE TITLE
Frontend followup work on Database connections UI

### ISSUE THREAD

**Issue by pavish** [mathesar-foundation/mathesar#3328]
As part of the [DB Connections spec](https://wiki.mathesar.org/design/specs/connections-page/) and https://github.com/mathesar-foundation/mathesar/issues/3294, we need the following:

* Modify database page route and bring it under connections:
  * Old: `/db/<connection_name>/`
  * New: `/connections/<connection_id>/`

* Use the term `Database Connection` wherever `Database` is used.
  * In multiple places in the app, we still use the term `Database`. Eg., the database page shows the connection nickname with a database icon and the term: Database. We need to look around the app and change this.
  * Note: This is only regarding the UI visible to the user. The terminology in code can be changed later.

* Resolve design items in this [HackMD doc](https://hackmd.io/@mathesar/SkA68dIBa) and implement the frontend work for them.

* If any of the above work is not strictly needed for `0.1.4`, move them into a different backlog issue.

**Comment by ghislaineguerin** [comment]
@pavish 
- I agree with limiting the page width. I had some other layout modifications in mind, but I don't think they will work well with the design, as you've mentioned. I have updated the Figma file to reflect the limited width.
- I agree with Sean about preferring tables. My idea was to introduce sorting headers at some point, which is what I appreciate about tables for listing things. I prefer cards when we have additional functionality to sort them. In the future, I'd like to include additional columns, such as 'Last Updated', and arrange them in default order based on that.
- Regarding your other suggestions, I will ensure that the design specs consider all user access levels and will also review the existing nomenclature/messaging throughout the app.

**Comment by kgodey** [comment]
Meta comment: I discussed this with @pavish in a 1:1, but I think we need some sort of design checklist that outlines the things we need to consider for each design – e.g. what viewports we should be designing against, ensuring that we are considering all design levels, ensuring that we're following the same nomenclature and UI design patterns, etc.

@pavish maybe you could start one? I don't think it needs to be comprehensive, just something based on the issues that came up here, we can add to over time.

**Comment by pavish** [comment]
@kgodey Yes, it's on my list, I haven't started any work on it. I will send a mail once I have a draft.

**Comment by seancolsen** [comment]
We chatted about this briefly at our design call today and agreed that we'll keep the design as-is for v0.1.4 (table layout for connections and `/db/<connection_id>` for the URL). We'll still discuss these design points for a later release though.

**Comment by seancolsen** [comment]
I'm closing this in favor of the following more specific issues:

- #3363
- #3362
- #3364
- #3365
- #3366
