### ISSUE TITLE
Add loading and error indications in the database page

### ISSUE THREAD

**Issue by pavish** [mathesar-foundation/mathesar#3330]
## Description
* The database page does not show any loading or error indicators when fetching the list of schemas.
* So far, the `common_data` loaded the schemas that were initially displayed in the database page, and hence the issue was not immediately visible in the UI.
* With the new Connections page, users can add a new connection and update existing ones. This leads to having to fetch the list of schemas while the page is open. This results in the page showing `Schemas (0)` and nothing else, while the schemas are being fetched or if an error has occurred while fetching.

<img width="1437" alt="Screenshot 2023-12-01 at 3 25 26 AM" src="https://github.com/mathesar-foundation/mathesar/assets/11850603/9530ece7-64e1-4650-a5a3-a4e1c7071834">

## Expected behavior
* The database page should show a loading indicator (a skeleton), while it's schemas are being fetched.
* Show error messages in the database page if the schema list fetch request has failed.

**Comment by MaYaNkKashyap681** [comment]
I want to work on this issue, could you please assign this issue to me?

**Comment by MaYaNkKashyap681** [comment]
Sure

**Comment by cerdo03** [comment]
Can anyone help in understanding in how the schemas are being fetched from the db? I dont see any other api being hit other than users/ in the network tab.

**Comment by MaYaNkKashyap681** [comment]
> Can anyone help in understanding in how the schemas are being fetched from the db? I dont see any other api being hit other than users/ in the network tab.

Right, i have also noticed same.

**Comment by pavish** [comment]
@cerdo03 @MaYaNkKashyap681 

There is a property called `common_data` which is rendered in the Django templates when the app loads for the first time. It contains the list of schemas, and the frontend does not make any API request. I'd recommend you to look at the code in `mathesar/templates/mathesar/index.html`, `mathesar/mathesar/views.py`, and `mathesar_ui/src/stores/schemas.ts`.

The issue above presents itself only when there are multiple databases connected to Mathesar, as noted in the description. There's [current ongoing work](https://github.com/mathesar-foundation/mathesar/issues/3311) to allow connecting to new databases from the UI.

You can do that manually by following these steps:
* Edit `docker-compose.dev.yml` and modify [this line](https://github.com/mathesar-foundation/mathesar/blob/1c71c263f21c6c95ca8ddcd41b6a387e3c270752/docker-compose.dev.yml#L69),
  from
  ```
  MATHESAR_DATABASES=(mathesar_tables|postgresql://mathesar:mathesar@mathesar_dev_db:5432/mathesar) 
  ```
  to
  ```
  MATHESAR_DATABASES=(mathesar_tables|postgresql://mathesar:mathesar@mathesar_dev_db:5432/mathesar),(duplicate_mathesar|postgresql://mathesar:mathesar@mathesar_dev_db:5432/mathesar),(second_db|postgresql://mathesar:mathesar@mathesar_dev_db:5432/newdb)
  ```
* Do not commit this change, only make it locally.
* Restart Mathesar.
* You should now see three database connections in the UI. Click on one of them, and you'll notice that the frontend sends a request to the `api/db/v0/schemas` endpoint.

**Comment by nikhilhenry** [comment]
@pavish 

Currently the schema store uses the deprecated **States** enum. As part of this issue, would that have to be refactored to use **RequestStatus** instead?

**Comment by pavish** [comment]
> Currently the schema store uses the deprecated States enum. As part of this issue, would that have to be refactored to use RequestStatus instead?

@nikhilhenry Yes, that would be ideal.
