### ISSUE TITLE
Modify schemas API to accept connection IDs instead of connection nicknames

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#3342]
## Context

I'm working on some frontend changes to [allow the user to edit connection names](https://github.com/mathesar-foundation/mathesar/issues/3333), and this work has had some cascading implications. Before we allow the user to edit the connection name, I want to make sure that everywhere we're handling connections on the frontend, we're using ids (not names) to identify them. I've started a [PR](https://github.com/mathesar-foundation/mathesar/pull/3341) with that refactoring work, and it's coming along nicely. However, I've hit a small snag.

## Problem

Our schemas API at `/api/db/v0/schemas/` requires the client to supply the connection nickname when listing schemas or creating a schema. I'm at a point in this refactor where I _can_ make changes on the front end to supply that nickname to the API, but it's going to be a bit weird on the frontend side because there are places where I need the nickname and only have the id. To me it seems much cleaner to change it on the backend side so that the API accepts ids instead of nicknames.

## The change I want

Currently the API requests look like this:

- `GET /api/db/v0/schemas/?database=mathesar_tables`
- `POST /api/db/v0/schemas/ { "name": "foo", "database": "mathesar_tables" }`

Instead, I'd like them to look like this:

- `GET /api/db/v0/schemas/?connection_id=3`
- `POST /api/db/v0/schemas/ { "name": "foo", "connection_id": 3 }`

**Comment by seancolsen** [comment]
@mathemancer, I've assigned this to you so that you can weight in and help decide if this is a change we should make.

Would it be an _easy_ change? If so, let's please do this. Maybe @Anish9901 could take it on?

Otherwise, if it would take more than an hour or two, then I can handle this on the front end.

**Comment by mathemancer** [comment]
@seancolsen I think it looks easy enough. I'm discussing with @Anish9901 on Matrix.
