### ISSUE TITLE
Resolve confusing terminology and iconography throughout UI for database connections

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#3363]
## Description

Some places throughout the UI use the term "db" or "database" when referring to an object that is actually a database _connection_. For example:

![image](https://github.com/mathesar-foundation/mathesar/assets/42411/704a9f78-03c7-4d72-8e38-598309889dde)

This UI is a vestige of an era in which Mathesar did not yet support multiple connections. Now that Mathesar allows users to configure database connections through the UI, it's possible for Mathesar to have multiple connections to the same database (potentially with different users). For this reason, it may be important for us to distinguish between a "database" and a "database _connection_".

This ticket first requires some design work to determine the exact changes to be made.

## Related

- #3362

**Comment by GopalVerma1303** [comment]
Hey @seancolsen. I confident in solving this issue. Can you please assign it to me?

**Comment by seancolsen** [comment]
Sorry @GopalVerma1303 but this issue is not eligible for community contribution. As noted in our [Contributor Guide](https://github.com/centerofci/mathesar/blob/develop/CONTRIBUTING.md) only [unassigned issues labeled "help wanted"](https://github.com/mathesar-foundation/mathesar/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3A%22help+wanted%22) are eligible for community contribution.

**Comment by seancolsen** [comment]
This is addressed now
