### ISSUE TITLE
Constrain the max width of the connections page content

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#3365]
## Current behavior

- The connections page at http://localhost:8000/connections/ shows a table of connections. The page content is fluid width, with no maximum width.

- On wide viewports this layout doesn't look great

    ![image](https://github.com/mathesar-foundation/mathesar/assets/42411/d925bf04-38e5-495e-81a4-23fec22008e5)

## Desired behavior

- The page content should have a reasonable max width. That content should be centered in the viewport for wide viewports. This is how some of our other pages work, like the database page and the schema page.

- The person implementing this issue should decide on a suitable max-width through some experimenting to see what looks good.

## Related

- #3366

**Comment by VandanaKumari18** [comment]
Hey @seancolsen , This issue really seems to be interesting. I have expertise that will enhance the outcome of this issue. Can you pls assign this to me ?

**Comment by srajansohani** [comment]
Hello @seancolsen  does this look good

<img width="1236" alt="Screenshot 2023-12-22 at 8 26 09 AM" src="https://github.com/mathesar-foundation/mathesar/assets/99042007/1ede7a6d-8125-4897-b799-0091ca46bd27">

**Comment by seancolsen** [comment]
@VandanaKumari18 You're welcome to work on this and submit a PR, but in general we don't assign tickets to new contributors, as noted in our [Contributor Guide](https://github.com/centerofci/mathesar/blob/develop/CONTRIBUTING.md). Once we've already merged a PR of yours, then we'll be happy to assign tickets to you after that. The reason for this policy is that in the past it has been a maintenance burden for us to manage ticket assignments while having an overwhelming volume of people fail to submit their first PR when initially expressing intent to contribute.

@srajansohani if you have changes to propose, please do so in a PR.

Both: also note that this issue now has one open PR already.
