### ISSUE TITLE
Update docs with regard to MATHESAR_DATABASES

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#3378]
- Make sure that our instructions for upgrading to v0.1.4 instruct Mathesar administrators to delete `MATHESAR_DATABASES` from their environment variables after upgrading.
- Make sure that (aside from the point above), we don't mention `MATHESAR_DATABASES` in the docs.

## Additional context

- Discussed in #3344

**Comment by seancolsen** [comment]
@Anish9901 I've assigned this to you so that you have all the documentation work within the v0.1.4 milestone.

**Comment by mathemancer** [comment]
For the deleting of `MATHESAR_DATABASES`, it's crucial that they don't delete that variable until _after_ updating (or they'll have to enter the credentials through the UI)

**Comment by seancolsen** [comment]
Addressed in #3227
