### ISSUE TITLE
Modifying database name, host name, or port number could result in a connection to a DB without Mathesar schemas

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#3384]
## Problem

- When editing an existing DB connection, a user can modify the host, port, and database name.
- This could be problematic if a user changes an existing connection to point to a database on which the Mathesar schemas have not already been installed.

**Comment by seancolsen** [comment]
## Potential solution: Disable those fields

- At the maintainers meeting today we agreed that we'd like to prevent users from modifying these fields by disabling them:

    <img src="https://github.com/mathesar-foundation/mathesar/assets/42411/24abdf56-9baf-4f1e-8ace-c4d6fb2652b5" width="400px">

**Comment by seancolsen** [comment]
@mathemancer @kgodey @Anish9901 As I'm getting my head deeper into this problem, I'm having second thoughts on our approach.

What happens if I have renamed my database, modified the host name, or changed the port? I understand that I could delete the connection and create a new one. But in that case I would lose all my metadata (e.g. display options, record summary templates, saved explorations, etc), right?

I'm a little hesitant to move forward with disabling these fields because I think users might actually be more likely to have legitimate reasons to edit them than they would be likely to edit them in such a way to point to a valid database without the Mathesar schemas.

I would think about solving this problem by other means:

- Improve our handling of error scenarios when the Mathesar schemas are missing. I understand this might not be straightforward since there are probably lots of different scenarios like this. Handling them all would be too costly in terms of developer time and application performance. But I imagine we might be able to identify one or two scenarios where a user would be most likely to encounter this kind of failure — say when loading the Database Page. At that point we could provide a means for the user to imperatively install the schemas. This would require some thinking and design across the entire stack, but it seems like it could provide a safety net for a variety of sticky situations.

- Allow users to store metadata _in_ the user database. I've been talking about this for a while, but I want to mention it again because here is a case that I think demonstrates the value of that approach. With metadata stored in the user database, a DB connection really becomes a tiny thing that I wouldn't mind deleting and re-creating.

This comment is certainly not to suggest that we attempt to forge ahead with either of those approaches any time soon, because they seem to be a lot of work. But rather: I'm inclined to hold off on this ticket, keeping it open but in the backlog.

**Comment by kgodey** [comment]
@seancolsen I agree that we need a more robust solution in the long term (I actually thought we agreed on that at the meeting, I remember @mathemancer bringing up the "we could provide a means for the user to imperatively install the schemas" idea during the discussion).

My suggestion was that we disable the fields as a quick, short-term solution to prevent the user from accidentally getting their Mathesar installation into a state they couldn't easily debug or recover from. I still think we should do that, and we can re-enable them when we implement a more robust solution.

**Comment by mathemancer** [comment]
> * Allow users to store metadata _in_ the user database. I've been talking about this for a while, but I want to mention it again because here is a case that I think demonstrates the value of that approach. With metadata stored in the user database, a DB connection really becomes a tiny thing that I wouldn't mind deleting and re-creating.

This is something I've been thinking about lots, but it's quite controversial, since it's yet another mathesar schema on the user DB (I'm thinking `msar_catalog`)

**Comment by seancolsen** [comment]
@kgodey ok, sorry I missed that during the meeting. Maybe I was too mentally preoccupied with taking notes? I don't know. In any case, yes, I'm fine with disabling the fields for now.

**Comment by seancolsen** [comment]
> we need a more robust solution in the long term

I added #3386 to track this more robust, long-term solution.

**Comment by kgodey** [comment]
> sorry I missed that during the meeting. Maybe I was too mentally preoccupied with taking notes? I don't know.

Sorry, didn't mean to call you out! It was a long meeting with lots of details and back and forth, totally understandable.
