### ISSUE TITLE
Array cells not styled correctly

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#3402]
| v0.1.3 | v0.1.4 |
| -- | -- |
| ![image](https://github.com/mathesar-foundation/mathesar/assets/42411/58ad732f-802d-4af9-a797-ad835ab5cb30) | ![image](https://github.com/mathesar-foundation/mathesar/assets/42411/33a08291-b8f5-4073-90b8-f398be3a517b) |

**Comment by seancolsen** [comment]
This is really weird. I'm no longer able to reproduce this. I'm confident that there haven't been any code changes merged into 0.1.4 in the past 3 days that would affect this behavior. 
That leaves me with the unsettling suspicion that this bug is somehow intermittent.

In my screenshot showing the bug, the column icon indicates correctly that the column type is a text array. That might suggest that the bug is on the front end side. However it could be that the backend is correctly returning the column type info while incorrectly returning the cell data.

Here is my pixel-for-pixel attempt at reproducing the bug today:

![image](https://github.com/mathesar-foundation/mathesar/assets/42411/693924ee-2438-4c7b-820f-2b390b8d6997)

I'm fairly confident in the consistency of the steps I took within the UI to arrive at this state. If we overlay these two images we can compare them to see what else might be different. In addition to the improper array formatting, there is one other difference which might offer a clue...

The formatting of first column is also problematic in my original bug screenshot! I didn't notice this before. When the bug is reproduced, the id numbers are left-aligned. When the bug is not reproduced, the id numbers are right aligned. That leads me to suspect that some part of Mathesar is incorrectly treating _all_ values as text (not just those text array values).

@mathemancer @pavish do either of you have any ideas as to what could be causing this or how a bug like this could be intermittent?

**Comment by pavish** [comment]
@seancolsen I'm not able to think of a possible reason on why this could have occurred. I'm pretty certain that it's a frontend issue though.

When you noticed the issue, was it on production or development mode? The vite server hot reload sometimes resets the stores and I've noticed issues like this occurring during development mode, which go away after a page reload.

**Comment by seancolsen** [comment]
Interesting, @pavish.

I observed the bug in development mode. I actually noticed it happen a few times before I eventually reported it. I'll try to inspect more closely if I can catch it again.

Unless @mathemancer has any further ideas I'll close this issue.

**Comment by seancolsen** [comment]
We discussed this in a meeting today and decided to close
