### ISSUE TITLE
Unified Docker image starts with a connection already added

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#3415]
- When I install Mathesar via the unified Docker image, I expect Mathesar to begin with no connections.
- Instead, I observe it to begin with one connection named `mathesar_tables`.

![image](https://github.com/mathesar-foundation/mathesar/assets/42411/a3a8fb9e-ea97-4595-a125-d7d85e1a88a2)

**Comment by pavish** [comment]
For the docker compose installation method:

On the `docker-compose.yml` file, there's a TODO item:

```
TODO Make the default empty once the connections UI is merged
```

The connections UI is merged, this TODO needs to be resolved.

**Comment by pavish** [comment]
Closed in https://github.com/mathesar-foundation/mathesar/pull/3417
