### ISSUE TITLE
Unable to scroll vertically on "create superuser" page

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#3418]
## Problem

This is the first page the user sees when installing Mathesar.

![image](https://github.com/mathesar-foundation/mathesar/assets/42411/4be7b520-0b05-4e47-80fa-f1179b3164da)

It doesn't allow vertical scrolling. Instead, content overflows the viewport.

## Steps to reproduce

I'm not actually sure how to view this page in development mode. Whoever picks this issue up will need to figure that out on their own. To point you in the right direction: this page appears to be a Django template — not a Svelte component.

**Comment by GopalVerma1303** [comment]
Hey @seancolsen! 
I have viewed this page in development mode. But can u please elaborate this issue (through the more images/video/gif). Because, I am able to vertically scroll the page content.
Thank you!

**Comment by seancolsen** [comment]
Hmmm...

I was able to view the page in development mode with these steps:

1. Run:

    ```
    docker exec -it mathesar_dev_db psql \
      -U mathesar \
      -d mathesar_django \
      -c 'truncate table mathesar_user cascade;'
    ```

1. Visit http://localhost:8000

But strangely, I wasn't able reproduce the bug there. I could scroll vertically on that page just fine. Very weird!!

Here's how I am able to reproduce it:

1. Run:

    ```
    docker run -it --rm -p 8000:8000 mathesar/mathesar-prod:0.1.4
    ```

1. Visit http://localhost:8001/


However, those reproduction steps make the feedback loop arduously slow to attempt fixing this bug. This is going to require some careful digging.

Due to this complexity, this issue is not tagged as "good first issue". Contributors are still welcome to pick this up, but you'll need to work independently to track this down. Due to the low priority of this issue, the maintainers team will not have the bandwidth to assist much with it.

**Comment by Sharath-1517** [comment]
Hey @seancolsen, the issue we face here happens when the viewport is made smaller right? Below is a video of the question I have for you.


https://github.com/user-attachments/assets/446e39ae-450b-4fc8-9976-d67d5ed83d18

I was not able to scroll on the page when I tried to scroll.

**Comment by seancolsen** [comment]
@Sharath-1517 I watched your video. It doesn't appear to have any sound. I'm not sure what your question is. It looks like you're able to reproduce the problem. So you're welcome to begin work on a fix. Please submit a PR if you'd like to ask any specific questions about your changes.

**Comment by Sharath-1517** [comment]
> @Sharath-1517 I watched your video. It doesn't appear to have any sound. I'm not sure what your question is. It looks like you're able to reproduce the problem. So you're welcome to begin work on a fix. Please submit a PR if you'd like to ask any specific questions about your changes.

Hey @seancolsen yeah it was just me reproducing the error because I just wanted to confirm that it was the issue. Thanks for clearing.

**Comment by Sharath-1517** [comment]
Hey @seancolsen I think I may have figured out a solution, but I need help with that. I want to remove all the super users that I have created currently. Do you have any suggestions for me to look out for or any leads that you could provide me for that?
Thanks!

**Comment by seancolsen** [comment]
@Sharath-1517 if you want to remove Mathesar users, try going here:

![image](https://github.com/user-attachments/assets/19b28b52-b23a-47b6-906e-333294d83e48)

> [!NOTE]
> If you have follow-up questions or other questions in the future which are not specifically related to the issue, then it's better to ask on [Matrix](https://wiki.mathesar.org/en/community/matrix) so as not to clutter up the thread here.

**Comment by Sharath-1517** [comment]
> @Sharath-1517 if you want to remove Mathesar users, try going here:
> 
> ![image](https://github.com/user-attachments/assets/19b28b52-b23a-47b6-906e-333294d83e48)
> 
> > [!NOTE]
> > If you have follow-up questions or other questions in the future which are not specifically related to the issue, then it's better to ask on [Matrix](https://wiki.mathesar.org/en/community/matrix) so as not to clutter up the thread here. 

Thanks for thr information Sean. Also just for your kind information I asked this question just because when I glanced through the docs I saw a piece of python code that redirects the user to the homepage if there is atleast one super user exists when I access the /auth/create_superuser page that's why I asked maybe if I remove that user I maybe able to access that page in development mode. Thanks! I'll make sure I approach my doubts in the Matrix.
