### ISSUE TITLE
Demo mode results in 5XX

### ISSUE THREAD

**Issue by mathemancer** [mathesar-foundation/mathesar#3433]
## Description

Mathesar is broken (as of 0.1.4) for Demo Mode. It doesn't load, and just says "Server Error (500)" instead.

## Expected behavior

Demo mode should work.

## To Reproduce

Change the `.env` file according to the comment to use the demo mode settings, try to build and start mathesar (dev environment is fine)

**Comment by Anish9901** [comment]
The settings module of the demo mode imports settings from `config.settings.production` which has `MATHESAR_MODE=PRODUCTION` & `DEBUG=FALSE`, now while using our dev container we have the `MODE=DEVELOPMENT` and `DEBUG=TRUE` this was leading to some weird behavior for `STATICFILES_DIRS` and hence the demo app was having trouble locating static files which was, in turn, causing the 500.

Setting `MODE=PRODUCTION` & `DEBUG=FALSE`, for demo mode fixes this issue.

**Comment by Anish9901** [comment]
We have different setting modules for dev(common_settings), production, and demo. Out of these, the common_settings are passed around in production which is passed to demo setting module with alterations made to a couple settings as mentioned in my previous comment for prod. We could fix the underlying issue by having a single settings file for all the modes and having a flag to switch between them.

**Comment by mathemancer** [comment]
It depends on the intended audience for the demo mode. For now, I agree it makes sense to run the demo mode using the dev settings, since most of the people we're directing there might be interested in the debug ouput and so on.
