### ISSUE TITLE
Column types not showing within shared tables and explorations

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#3455]
## Steps to reproduce

1. Create a table share
1. View the shared table page
1. Within the column header cells, expect to see type icons alongside the column names.
1. Instead, observe question marks for all columns.
1. Expect to see numbers right-aligned.
1. Instead, see numbers left-aligned (because they are being treated as text).

    ![image](https://github.com/mathesar-foundation/mathesar/assets/42411/e62571db-5f2a-4647-8a66-6bbfa3869e58)

**Comment by pavish** [comment]
Same root cause as https://github.com/mathesar-foundation/mathesar/issues/3452
