### ISSUE TITLE
Issue with Confirmation Message Variables After Moving Column to Linked Table

### ISSUE THREAD

**Issue by ghislaineguerin** [mathesar-foundation/mathesar#3462]
## Description
The confirmation message fails to properly render variables after a column is moved to a linked table.

## Expected behavior
After moving a column to a linked table using the 'Move Column to Linked Table' option, the system should display a confirmation message that accurately renders the names of the moved column(s) and the target table.

## To Reproduce
1. Navigate to a table linked to another table.
2. Use the 'Move Column to Linked Table' feature to move a column.
3. Observe the confirmation message, which incorrectly displays variable syntax like this:
![image](https://github.com/mathesar-foundation/mathesar/assets/845767/d8336ea9-5493-4cc2-8cd8-d3ac4033a212)

**Comment by pavish** [comment]
Fixed in https://github.com/mathesar-foundation/mathesar/pull/3472
