### ISSUE TITLE
Docker compose upgrade instructions don't actually pull a new image

### ISSUE THREAD

**Issue by mathemancer** [mathesar-foundation/mathesar#3467]
## Description

Due to hasty reviewing on my part, I didn't notice that the docker compose upgrade instructions don't actually pull the new image if they still have the old one (they likely do):

```
docker compose -f /etc/mathesar/docker-compose.yml up \
  --force-recreate --build service
```

Therefore, no upgrade occurs.

## Expected behavior

We should instead advise them to use:

```
sudo docker compose -f docker-compose.yml up --pull always -d
```

## Additional context

Discovered this while working on #3465 , but that user's core issue is likely a bit different, so I'm creating a separate ticket and docs PR for this.

**Comment by kgodey** [comment]
Done in https://github.com/mathesar-foundation/mathesar/pull/3468
