### ISSUE TITLE
CSRF Failed Error

### ISSUE THREAD

**Issue by ghislaineguerin** [mathesar-foundation/mathesar#3497]
## Description
The error message 
"CSRF Failed: Origin checking failed - https://internal.mathesar.org/ does not match any trusted origins."
is appearing when performing certain actions in Mathesar like creating a new internal db or saving a record. 

## Additional context
This happened while testing internal.mathesar.org

**Comment by Anish9901** [comment]
Here is the screenshot of the error for reference: 
<img width="699" alt="Screenshot 2024-03-20 at 2 44 34 PM" src="https://github.com/mathesar-foundation/mathesar/assets/52523023/38f07591-e18d-4ad6-8c37-30bb009a81ae">


For the sake of QA, I've temporarily fixed this by following this [SO](https://stackoverflow.com/a/71482883) answer but this issue will need to be investigated more to pinpoint the actual problem.

**Comment by Anish9901** [comment]
Closed by #3499
