### ISSUE TITLE
Table name validation not working when extracting a column

### ISSUE THREAD

**Issue by ghislaineguerin** [mathesar-foundation/mathesar#3498]
## Description
There's an issue with table name validation when creating them via "Extract Columns to Table". 

When the table is created from scratch it will show a warning in the table creation form. However that warning is not showing here and it generates an error on save:
<img width="995" alt="image" src="https://github.com/mathesar-foundation/mathesar/assets/845767/34164edd-fe39-401a-9c97-2f3333ca92f4">

Once the invalid name table is saved the entire schema can't be accessed:
<img width="646" alt="image" src="https://github.com/mathesar-foundation/mathesar/assets/845767/1439adfa-ecde-446c-9960-b3aea62ed564">

## Expected behavior
Mathesar should prevent errors in table creation by warning about invalid characters.

## To Reproduce
Go to Mathesar:
- Attempt to create a new table by extracting a column.
- Use an invalid character in the name.

**Comment by kgodey** [comment]
This should be handled by the backend refactor, we'll double check before the beta is out.

**Comment by seancolsen** [comment]
This appears to be fixed now.
