### ISSUE TITLE
Layout Issues with Japanese Translation

### ISSUE THREAD

**Issue by ghislaineguerin** [mathesar-foundation/mathesar#3500]
## Description
The Data Explorer's top bar experiences layout issues when language set to Japanese, with a button's text wrapping vertically, causing an incorrect height. This issue does not occur in saved explorations.

## Expected behavior
The layout should look like this:
<img width="550" alt="image" src="https://github.com/mathesar-foundation/mathesar/assets/845767/a7523dff-fa12-4c7b-bbcd-e76a844904b1">

## To Reproduce
- Set language to japanese
- Go to data explorer

## Additional context
<img width="1363" alt="image" src="https://github.com/mathesar-foundation/mathesar/assets/845767/cf5b08f2-777f-44e4-9714-f5cbf2448b77">

**Comment by pavish** [comment]
Fixed in https://github.com/mathesar-foundation/mathesar/pull/3501
