### ISSUE TITLE
Documentation issues - 0.1.6

### ISSUE THREAD

**Issue by pavish** [mathesar-foundation/mathesar#3505]
Install from scratch:
- Git repo link uses centerofci link instead of mathesar-foundation
    > git clone https://github.com/centerofci/mathesar.git .
- `mv static_files /mathesar/static/mathesar` should be `mv static_files ./mathesar/static/mathesar`
- Remove `static_files.zip` once extracted
- User database creation is no longer relevant and should be removed: `CREATE DATABASE your_db_name OWNER mathesar;`

Upgrades:
- 0.1.6 upgrade instructions are not present in the docs.
  - (I tested the setup based on previous upgrade instructions)

Upgrade from scratch:
- Upgrade to 0.1.5 > Section: For installations done from scratch > Link used for text `are the same as for 0.1.4` points to a location that's not found
- Step: `Pull the latest version from the repository` should pull latest tag
- Step: `Update Python dependencies` should install from `requirements-prod.txt`

**Comment by Anish9901** [comment]
> mv static_files /mathesar/static/mathesar should be mv static_files ./mathesar/static/mathesar

This was fixed in #3503

**Comment by seancolsen** [comment]
Done in #3507
