### ISSUE TITLE
Password change error message UI/UX

### ISSUE THREAD

**Issue by hitenvidhani** [mathesar-foundation/mathesar#3563]
## Description
Some issues were discussed in this PR(https://github.com/mathesar-foundation/mathesar/pull/3536#issuecomment-2059968281) regarding password change error messages display.
1. Error messages display in which language when a user in Japanese mode changes password?
2. Alignment of error message.
3. Some other issues which I saw while testing this([Video](https://github.com/mathesar-foundation/mathesar/assets/60215053/c9ed3f03-c3c5-4687-bd39-acefee68a071)):
Notice that I have selected Japanese mode but there are many untranslated pieces of text

## Expected behavior

1. Messages should be in Japanese which is happening currently so no changes required there
![image](https://github.com/mathesar-foundation/mathesar/assets/60215053/84d9f382-e4b6-4ddd-a2b2-882749124db3)
2. Alignment of the messages should be in sync with the button above the error message
3. All the text should be in Japanese, I suppose. If not, I believe at least the info message should be in Japanese.

## To Reproduce

Try setting or changing password that it invalid (which doesn't contain any special character)

## Environment
 - OS: (_eg._ macOS 10.14.6; Fedora 32)
 - Browser: (_eg._ Safari; Firefox)
 - Browser Version: (_eg._ 13; 73)
 - Other info:

## Additional context

```[tasklist]
### Tasks
```

**Comment by seancolsen** [comment]
@hitenvidhani This issue is a bit hard to understand. Before we proceed, I'd like you to clean it up.

- You said:

    > Messages should be in Japanese which is happening currently so no changes required there

    If you don't think any changes are required, then please remove all reference to this. You've included a screenshot which seems to show things working as you expect. If that's the case, then please remove the screenshot too. It's distracting and confusing as I'm trying to understand the work required here.

- You said:

    > Alignment of the messages should be in sync with the button above the error message

    I'm not sure what you mean specifically. Are you expecting the left edge of the error message to be horizontally aligned with the left edge of the cancel button? If so, I'd rather not spend time worry about that right now. If it's something you feel strongly about, then please open an issued dedicated to discussing this specific problem in isolation. Describe it clearly with a screenshot (of the UI in English).

- You said:

    > Some other issues which I saw while testing this([Video](https://github.com/mathesar-foundation/mathesar/assets/60215053/c9ed3f03-c3c5-4687-bd39-acefee68a071)). Notice that I have selected Japanese mode but there are many untranslated pieces of text. All the text should be in Japanese, I suppose. If not, I believe at least the info message should be in Japanese.

    This is good feedback and probably represents some changes we ought to make. But it's really hard to decipher from the way you've described it. Please open a new issue for this specific problem. Clearly describe the steps (sequentially) to reproduce the problem. Describe your expected behavior and your observed behavior. Include a screenshot (which will be easier to follow than your video). Once that ticket is open we can discuss further.

Unless I'm missing something, I think we can close this issue once you've taken the steps above.

**Comment by hitenvidhani** [comment]
Created a new issue https://github.com/mathesar-foundation/mathesar/issues/3603, hence closing this one.
> Are you expecting the left edge of the error message to be horizontally aligned with the left edge of the cancel button?
Yeah, but it can be ignored currently as you said.
