### ISSUE TITLE
Missing favicon

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#3605]
Mathesar should have a favicon set. At one point I think we did have this. It appears there is some problem with this now

![image](https://github.com/mathesar-foundation/mathesar/assets/42411/ae3e8e3c-1424-4e3a-95e5-bc0ecf7b0e09)

We need to troubleshoot what is happening here before we identify the right sort of fix.

Originally reported by @kgodey [in Matrix](https://matrix.to/#/!kpLRqiyQwsndKhBIvd:matrix.mathesar.org/$9fJ97TEY3f-djcKuIz8SmoVsnFokK9qYMMuyVDbGWjo?via=matrix.mathesar.org&via=matrix.org)

## See also

- #1520 which is more elaborate (multiple dynamic favicons) and lower priority

**Comment by bobyficher** [comment]
![image](https://github.com/mathesar-foundation/mathesar/assets/97780571/94527eac-294c-4a26-94e7-b2cd6cc26352)

**Comment by seancolsen** [comment]
@bobyficher I'm not sure what you're intending to communicate with the above screenshot, but I'll say that appears to be from our marketing site, https://mathesar.org. This issue is 
about the Mathesar _application_, not the marketing site.

**Comment by hitenvidhani** [comment]
It's not missing but this is intended.
[Ref](https://github.com/mathesar-foundation/mathesar/blob/aaac7dbc3d5c4d4d366b242f9f58727999ebfbc2/mathesar/templates/mathesar/base.html#L8)

**Comment by linux478** [comment]
if no one is working on this, I would like to take a shot at it as my first experience to contribution to an open source project.

**Comment by seancolsen** [comment]
Sure go ahead and submit a PR, @linux478. Reach out on Matrix if you have any questions.

**Comment by pavish** [comment]
Removing the `regression` label since we never actually had a favicon.

**Comment by kgodey** [comment]
@pavish I could have sworn we had a favicon...

**Comment by Sharath-1517** [comment]
I'd like to work on this issue. Just for your kind information, I have tried to fix this issue and has fixed it. Can I raise a PR for it?
