### ISSUE TITLE
Unable to remove a comment on a schema

### ISSUE THREAD

**Issue by Anish9901** [mathesar-foundation/mathesar#3638]
## TODO
Refactor `comment_on_schema` SQL functions to remove the comment on a schema if the comment is NULL instead of returning NULL.

**Comment by seancolsen** [comment]
@Anish9901 why is this needed for beta?

**Comment by Anish9901** [comment]
Well..., it's quite low effort and we've already done it for tables and columns, also we currently set the comment to `''` instead of `NULL` when removing it.
