### ISSUE TITLE
roles.add

### ISSUE THREAD

**Issue by pavish** [mathesar-foundation/mathesar#3670]
* API adds a new role

Request parameters:
```
database_id: Database['id'];
name: string;
login: boolean;
password?: string; // Should be present if login is true
```

Response:
`RoleInfo` class (Refer `mathesar/rpc/roles.py`)

**Comment by Anish9901** [comment]
@pavish is the `login` flag necessary? I think we could use the `password` parameter to infer whether a login role is requested.
