### ISSUE TITLE
Change structure of columns metadata

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#3701]
For my work on the table page, I need some changes to the way we handle columns metadata through the API.

I basically need all the same changes that I performed in #3672, but done for columns instead of tables.

**Comment by seancolsen** [comment]
@Anish9901 I've assigned you to this. Do you think you could pause work on the explorations-related APIs and switch over to this? Do you need any additional detail? Or is my description above clear enough? I think if you read over the commits I made in #3672 it should hopefully make sense.

**Comment by Anish9901** [comment]
Yes, I could switch over to this. Your description is clear enough, I'll ask for more details if I need any.
