### ISSUE TITLE
Add tables and columns properties to RPC joinable_tables API

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#3713]
In the REST API, the joinable_tables API returned an object like this:

```json5
{
  "joinable_tables": [
    // ...
  ],
  "tables": [
    // ...
  ],
  "columns": [
    // ...
  ],
}
```

The corresponding RPC API only returns an array of joinable table objects.

The front end needs the `tables` and `columns` properties too. Can we please add those back?

**Comment by Anish9901** [comment]
@seancolsen 
Instead of having `tables` and `columns` separate are you okay if its combined?

**Before**
```json
{
  "tables": {
    "10": {
      "name": "Authors",
      "columns": [1, 2, 26]
    }
  },
  "columns": {
    "1" : {"name": "First Name", "type": "text"   },
    "2" : {"name": "Last Name" , "type": "text"   },
    "26": {"name": "id"        , "type": "integer"}
  }
}
```
**After**
```json
"tables": {
  "10": {
    "name": "Authors",
    "columns": {
        "1" : {"name": "First Name", "type": "text"   },
        "2" : {"name": "Last Name" , "type": "text"   },
        "26": {"name": "id"        , "type": "integer"}
     }
  }
}
```

**Comment by seancolsen** [comment]
> are you okay if its combined?

I [replied](https://github.com/mathesar-foundation/mathesar/pull/3718#pullrequestreview-2209007554) in the PR.
