### ISSUE TITLE
Resolve all TODO_BETA code comments

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#3744]
https://github.com/search?q=repo%3Amathesar-foundation%2Fmathesar%20TODO_BETA&type=code

## See also

- #3820

**Comment by mathemancer** [comment]
I grepped, and it seems this is only relevant in the front end.

**Comment by kgodey** [comment]
Leaving this in the main beta milestone, but @seancolsen will go through the comments and prioritize them individually. @seancolsen, I assume you'll make separate issues or something like that if they're not blockers.
