### ISSUE TITLE
Modify `records.delete` RPC method to permit deleting records via stringified primary key values

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#3752]
From a table with a numeric primary key column, I can delete records via an RPC request like this:

```json5
{
  "jsonrpc": "2.0",
  "method": "records.delete",
  "id": 0,
  "params": {
    "database_id": 1,
    "table_oid": 692359,
    "record_ids":[
      1
    ]
  }
}
```

But, with the REST API, the front end has actually been sending _stringified_ primary key values. So it would be easier if I could send this:

```json5
{
  "jsonrpc": "2.0",
  "method": "records.delete",
  "id": 0,
  "params": {
    "database_id": 1,
    "table_oid": 692359,
    "record_ids":[
      "1"
    ]
  }
}
```

Initially, I thought: _"hmmm, sending pk values in the correct type would be more idiomatic, so why not change this on the front end?"_ But unfortunately this doesn't appear to be an easy change to make. It's possible of course. But it's hard to tell how much time. I spent 30 minutes and just ended up uncovering a bunch of problems fanning out across different modules.

So if this would be easier to change on the backend, I'd rather do that.

**Comment by seancolsen** [comment]
If this is hard to implement on the backend, please feel free to punt it back to me and I'll put in the work to solve it on the front end. In a perfect world we'd fix this on the front end. But I'm also trying to identify the path of least resistance.

**Comment by mathemancer** [comment]
I'll look.
