### ISSUE TITLE
database_privileges.set_for_roles

### ISSUE THREAD

**Issue by pavish** [mathesar-foundation/mathesar#3773]
```
database_id;
set_privileges: [
  {
     role_oid;
     privileges: SET<CONNECT|CREATE|TEMPORARY>
  },
  {
     role_oid;
     privileges: SET<CONNECT|CREATE|TEMPORARY>
  }
]
```

Should return `Array<DatabasePrivileges>`

`DatabasePrivileges` from https://github.com/mathesar-foundation/mathesar/issues/3662

**Comment by mathemancer** [comment]
I did some quick tests to make sure we can do this transactionally. Good news: We can!

So, I think we're good to proceed with this function.

**Comment by mathemancer** [comment]
@pavish I updated the spec just a bit to simplify it and make it consistent with other similar functions:

```
database_id: <int>
privileges: [
  {
     role_oid: <int>,
     direct: SET<CONNECT|CREATE|TEMPORARY>
  },
  {
     role_oid: <int>,
     direct: SET<CONNECT|CREATE|TEMPORARY>
  },
  ...
]
```
