### ISSUE TITLE
Intermittent failure to display updated table name

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#3867]
I'm observing a tricky bug when editing a table name via the table inspector. The name is consistently updated in PostgreSQL. But in the UI sometimes new name is updated and sometimes not. I can't seem to identify any correlation between failure and specific reproduction steps. It's also difficult because it doesn't seem to be perfectly random either. For example, I had it succeed 25 times in a row. Then refreshed the page and had it fail 25 times in a row. I've also seen it succeed on the first try and fail on the second. And I've seen it fail on the first try too. My hunch is that there's some sort of race condition in the front end code.

One more clue: I've noticed that sometimes the entire table refreshes after I update its name — as in, the _records_ reload too. And I _think_ it's those times when the renaming succeeds. I'm not positive about this though.

**Comment by pavish** [comment]
I'm re-opening this bug as I'm facing it while performing QA. Here are the latest reproduction steps:
* Create a table from scratch. It's automatically named `Table {n}`
* Rename to `ABC`.
* Notice the request succeeds, but the name still displaying as `Table {n}`
