### ISSUE TITLE
Incorrect "added column" indicators in explorations

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#3871]
These indicators are supposed to show which (and how many) columns are added to the exploration, but they're broken, I'm assuming due to the fact that column ids are no longer unique across separate tables.

![image](https://github.com/user-attachments/assets/2da30060-f157-4aa8-9213-1bc3cbe4165e)

While it might be tempting to think we could fix this by qualifying columns with their respective table oids, I don't think that's the solution either. If table `a` links to table `b` twice through two separate foreign key columns, then we need to make sure not to conflate those column indicators as well. (Indeed, that's actually a bug in 0.1.7 that I just [verified](https://internal.mathesar.org/db/1/4608/explorations/33/edit/).) I think the indicators need to rely on the full join path to be unique.

**Comment by seancolsen** [comment]
I'm wondering if we should remove the column indicators altogether. They're useful. But are they useful _enough_ to justify the extra time to fix, especially given that we may be re-thinking explorations more deeply in the near future?

This is a question of priorities that I think @kgodey should decide on. 

@ghislaineguerin and @pavish might have opinions too.

What do you think? Spend the time to fix these? If so, which milestone? Or remove the feature temporarily? Or permanently?

**Comment by ghislaineguerin** [comment]
@seancolsen 
We should hide it for now if it's causing issues, but we definitely need a way to indicate when a column has been added. The lack of feedback would cause a poor user experience.

**Comment by kgodey** [comment]
I’m fine with not implementing this for now, but @seancolsen could you please make an issue that tracks adding these back? You can put it in 0.2.0 for now.

**Comment by seancolsen** [comment]
Cool.

I'm closing this issue in favor of more succinct versions:

- #3888
- #3889
