### ISSUE TITLE
Wrong colors for table pills in Link Table dialog

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#3886]
In the CreateLink dialog, the colors of these table pills need to be swapped to match the colors of the pills in the diagram.

![image](https://github.com/user-attachments/assets/179bb1f6-113e-4b7a-870e-caeac3c2d452)

**Comment by adityaS011** [comment]
can I work on it @seancolsen

**Comment by adityaS011** [comment]
can I work on it @seancolsen

**Comment by seancolsen** [comment]
Thanks @adityaS011, feel free to submit a PR.

**Comment by dev10s** [comment]
can i work on it @seancolsen .

**Comment by adityaS011** [comment]
@seancolsen I am not able to setup server so I can't move forward with this I tried many alternative can't figure out the issue it says port don't exisit.
@devrupchowdhury u can move forward with this if u want
