### ISSUE TITLE
Unable to Assign Child Role

### ISSUE THREAD

**Issue by ghislaineguerin** [mathesar-foundation/mathesar#3900]
## Description
When attempting to assign a child role, an error occurs. In this case, I attempted to assign the role "Test1" to the child role "Test2," (both created by my role mathesar) but the operation failed with the following error message:

<img width="509" alt="image" src="https://github.com/user-attachments/assets/bd86e49a-7533-464a-8f13-af666c07479a">

Both roles appear in the list as if they exist, I can assign them to a collaborator and use them, but the operation still fails during execution.

## Expected behavior
If both roles are shown as existing, the GRANT command should execute without errors.

## To Reproduce
- Create two login roles
- Make one role the child of the other role

**Comment by mathemancer** [comment]
This is back end. The role-granting SQL function isn't correctly quoting identifiers.
