### ISSUE TITLE
Server error (500) when there's a single database connected and admin user is not a collaborator

### ISSUE THREAD

**Issue by pavish** [mathesar-foundation/mathesar#3903]
## Description
* Create a database if nothing exists. Make sure there's only one database at the end.
* Open the database, remove yourself from the collaborator list.
* Refresh the page. Or change url to homepage on the browser url bar (eg., `localhost`).
* Notice a server error.
* This also happens when directly visiting any database url where the user is not a collaborator, and even when visiting a url for a non-existent database eg, (`http://localhost/db/10000/`).

## Probable cause
* Since the user is not a collaborator on the database, creating the `common_data` would fail causing this 500.

## Expected behavior
* If the user is an admin, there should not be an error and the UI should show the database page with the error/add-yourself-as-a-collaborator message inside the page.
* If the user is not an admin, the url should redirect to `/databases`.

**Comment by Anish9901** [comment]
Fixed in #3948
