### ISSUE TITLE
Action buttons appearing like they're disabled in inspector

### ISSUE THREAD

**Issue by pavish** [mathesar-foundation/mathesar#3906]
## Description
* Open inspector.
* Notice some buttons appearing as follows:
* ![Screenshot 2024-10-01 at 7 05 47 PM](https://github.com/user-attachments/assets/1cbd534f-abb8-4f12-b73c-08476319865c)

## Expected
* The buttons should not look like they're disabled.

**Comment by seancolsen** [comment]
For reference, here's what they looked like before:

![image](https://github.com/user-attachments/assets/69d817ea-c36a-440a-a1da-655e3ed862ba)
