### ISSUE TITLE
Unable to drag columns after dragging one column

### ISSUE THREAD

**Issue by pavish** [mathesar-foundation/mathesar#3908]
## Description
* Open a table
* Drag and move a column. Notice that it moves to the new location -> Good.
* Try to drag and move another column. Notice that nothing happens -> Bad.
* See video:

https://github.com/user-attachments/assets/76ff984e-e741-4eb0-95ee-6164a959d49f

## Expected behavior
* We should be able to drag and move columns.

**Comment by seancolsen** [comment]
@pavish #3909 should fix this too
