### ISSUE TITLE
Save & Discard buttons always shown when viewing user

### ISSUE THREAD

**Issue by pavish** [mathesar-foundation/mathesar#3932]
## Description
* Click on a standard user from the user's page
* Notice the following:
* <img width="1083" alt="Screenshot 2024-10-07 at 6 48 50 PM" src="https://github.com/user-attachments/assets/bde85f0c-76b5-4439-80de-ddfdcb42bdeb">
* The "Discard Changes" and "Save" button are always shown.
* Clicking on Discard changes the value of Role to "Admin".
* These buttons do not disappear even after saving again.
* This seems to a broader issue stemming from some change in the `FormSubmit` component.
* Possibly related to https://github.com/mathesar-foundation/mathesar/issues/3878

## Expected behavior
* These buttons should only show when there is a change in the form.

**Comment by seancolsen** [comment]
As part of the 0.2.0 release notes, I verified that I in fact able to reproduce this on 0.1.7. Thus I've removed this `regression label`. As far as the release is concerned, this is a bug, not a regression.
