### ISSUE TITLE
Incorrect owner information shown for the public schema

### ISSUE THREAD

**Issue by Anish9901** [mathesar-foundation/mathesar#3957]
## Description

<img width="1486" alt="Screenshot 2024-10-14 at 7 22 11 PM" src="https://github.com/user-attachments/assets/183cde46-2175-48ae-bb81-f8f5299d9d9f">

**Comment by mathemancer** [comment]
@Anish9901 Please check if this is still a problem, and close if it's not.

**Comment by Anish9901** [comment]
I'm unable to reproduce this.
