### ISSUE TITLE
Uploadable filetypes can't be imported

### ISSUE THREAD

**Issue by mathemancer** [mathesar-foundation/mathesar#3965]
## Description

We currently allow uploading and storing a number of filetypes that we don't actually support for import:

- json
- Excel
- etc. (probably)

## Expected behavior

We should throw a reasonable error whenever a user attempts uploading a file type we can't import.

## To Reproduce

Try to import an Excel file in Mathesar.

## Environment
 - OS: (_eg._ macOS 10.14.6; Fedora 32)
 - Browser: (_eg._ Safari; Firefox)
 - Browser Version: (_eg._ 13; 73)
 - Other info:

**Comment by aniketkulkarni17** [comment]
Hi, 
I would like to work on this issue. Can you please assign this issue to me? Also, would like to know which filetypes should be accepted so that I can handle the errors for other file types

**Comment by mathemancer** [comment]
This is still blocked pending product approval. It's not clear when/if we're going to support other filetype uploading in Mathesar.

**Comment by mathemancer** [comment]
Okay, I've had a back channel conversation and done some thinking. Go ahead and work on this if you'd like, @aniketkulkarni17 . As mentioned in #3992, you will be assigned to this issue if you raise a reasonable PR to attempt to solve it. Thank you!
