### ISSUE TITLE
Github sponsor page takes to deprecated `centerofci`

### ISSUE THREAD

**Issue by Aritra8438** [mathesar-foundation/mathesar#3986]
## Description
In the docs, [here](https://docs.mathesar.org/latest/#donate), the github sponsor page takes to [https://github.com/sponsors/centerofci](https://github.com/sponsors/centerofci), which is deprecated.

## Expected behavior
It should be changed to [https://github.com/sponsors/mathesar-foundation](https://github.com/sponsors/mathesar-foundation).

**Comment by seancolsen** [comment]
Thanks for reporting this, @Aritra8438. I'll fix it today.
