### ISSUE TITLE
Implement `users.delete` RPC function

### ISSUE THREAD

**Issue by mathemancer** [mathesar-foundation/mathesar#4000]
We need to implement a `users.delete` RPC function to replace the `DELETE /api/ui/v0/users/{userId}/` endpoint.

The function signature should be:

```python
@rpc_method(name='users.delete')
@http_basic_auth_superuser_required
@handle_rpc_exceptions
def delete(
        *,
        user_id: int,
) -> None:
```

See [the wiki](https://wiki.mathesar.org/projects/2024/architecture-transition/rpc/#functions) for more context.

**Comment by nilaygit-10721** [comment]
Hello @mathemancer , could you please guide me to the specific file or directory where I should implement the users.delete RPC function as outlined? I want to ensure I'm working in the right section of the codebase. Thank you!

**Comment by mathemancer** [comment]
For the back end portion, you'll need to look in the `mathesar/api/rpc/` directory. You need to create a new file `mathesar/api/rpc/users/base.py` for this, since it's the first `users` namespace RPC function.

**Comment by nilaygit-10721** [comment]
check my pr https://github.com/mathesar-foundation/mathesar/pull/4014
