### ISSUE TITLE
Two typos in the docs folder

### ISSUE THREAD

**Issue by TheGiraffe3** [mathesar-foundation/mathesar#4033]
## Description
There are two typos in the `docs/docs` folder of the repository.

## Expected behavior
No typos.

## To Reproduce
Open the files and observe bug.

## Environment
N/A; happens on all devices.

## Additional context
Not exactly a bug, but the pull request template said to open an issue before submitting the PR.
There is a pull request to fix this: #4034.

**Comment by seancolsen** [comment]
@TheGiraffe3 FYI, for small changes like this in the future, no need to open an issue. A PR is fine on its own.

**Comment by TheGiraffe3** [comment]
Closing; #4034 was taken over by #4045 and the issues fixed.
