### ISSUE TITLE
Remove "Shortcuts" menu

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#4048]
I would like to remove this menu:

![image](https://github.com/user-attachments/assets/df109928-d24e-42bf-af82-d2851c0c5320)

I'd like to put the content into this menu:

![image](https://github.com/user-attachments/assets/8fb19cea-c2ce-4004-8a47-239320b67549)

And I'd like to improvise the design for that during implementation

## Related

- #3287
- #3899

**Comment by zackkrida** [comment]
Nice idea, I like the paradigm of a contextual "quick actions" panel for each layer (DB, Schema, Table) instead of one global one.

**Comment by seancolsen** [comment]
Ghislaine and I discussed this in a [call](https://tldv.io/app/meetings/6756f0de62a36e00136ec11a) on 2024-12-09. We agreed that, for the sake of simplicity and implementation time, we will _not_ attempt to move the "shortcuts" items into the breadcrumb separator dropdown menus.

**Comment by kgodey** [comment]
Thanks for the update, @seancolsen.
