### ISSUE TITLE
Allow users to hover over record-level error messages

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#4083]
## Current behavior

- We have these record-level error messages which display after a failed INSERT.

    ![image](https://github.com/user-attachments/assets/a0ac19ce-42a4-453e-ab0d-4ce99504808d)

    You can get one of these to appear if you set a NOT NULL constraint for a column and then try to insert a record.

- The error message is visible when the user hovers the corresponding row header cell. But when the user tries to hover over the message itself, the message disappears.

## Desired behavior

- Users should be able to hover over the error message itself in case they want to copy text out of it.

(Originally reported by @zackkrida [here](https://github.com/mathesar-foundation/mathesar/issues/4071#issuecomment-2545945757).)

**Comment by sharath-1517** [comment]
I'd like to work on this issue. Can I?

**Comment by seancolsen** [comment]
Sure, @sharath-1517. And since I've seen you commenting on a number of issues lately, I'll also add that, in general, there's no need to get permission to work on an issue. So long as it's `ready`, `help wanted`, and not already assigned to anyone, you're welcome to submit a PR for it.
