### ISSUE TITLE
Support for listing database views

### ISSUE THREAD

**Issue by kgodey** [mathesar-foundation/mathesar#455]
Mathesar should support viewing a list of all existing views in a given schema.

## Scenarios
1. Users should be able to browse through a list of all available views in the currently open schema. This should probably happen in a different page with a paginated view.
    1. Error scenario: The list of views cannot be loaded from the backend due to an error.
2.  Users should be able to access all views through the left pane.
    1. Error scenario: The list of views cannot be loaded from the backend due to an error.
3.  Users should be able to search for views by name from the left pane, even if they are not visible in the left pane.
    1. Error scenario 1: The user tries to search for a view but no views are found with that name.
    2. Error scenario 2: The API call for the search fails for some reason (e.g. backend server is down)
4.  Users should be able to open a view in a tab. The design for what happens when a view is opened will be covered in #466.
    1. Error scenario: The user tries to open a view but the action fails for some reason (e.g. the view has been deleted by another user in the last few seconds)
   
## Design Notes
- Views are a new type of database object so we should consider how to present them to the user. Views are contained within a schema just like tables, but they are used for different purposes. It's highly likely that non-technical users will not understand the difference between tables and views easily, so this is something we need to emphasize in the design.
-  Please note that we cannot always show all views in the left pane. If there are hundreds of views, rendering all of them will make the product slow. We do not need a design solution here - #723 will address how to show hundreds of views, but it's worth keeping in mind.
- There are two different types of views - materialized views and regular views. They should have pretty similar functionality so I'm not sure if it's worth distinguishing them in the list of views, but it might be useful to have different icons or something like that.

## Additional Context
- Previous design discussion: #669 
- Materialized view support: #834 
- [Here's a tutorial about Postgres views](https://www.postgresqltutorial.com/postgresql-views/), in case that's helpful.

**Comment by kgodey** [comment]
@ghislaineguerin @pavish @mathemancer @seancolsen This issue has been updated and is ready for review. Please look through it and unassign yourself after you've added any feedback that you might have.

**Comment by pavish** [comment]
* > Users should be able to browse through a list of all available views in the currently open schema. This should probably happen in a different page with a paginated view.

   I think instead of a new page for views of the open schema, we can add an option/link in the schemas listing page to list each schema's tables and views.

* Views and tables exist on the same namespace in database i.e the name of the views and tables cannot be the same. This is a general point, just in case it helps @ghislaineguerin in the design process.

**Comment by seancolsen** [comment]
@kgodey I suggest that at first we _do show all_ the views in the left pane. Then, in the process of working on #723 we re-design the left pane to handle longer lists of views and tables. I recon that designing an intuitive way to manage large sets of tables and views might present some tricky UX questions, and I don't think we should let it get in the way of building the more important parts of the views system for now.

**Comment by mathemancer** [comment]
> Users should be able to access recently updated views through the left pane.

There are a number of kinds of "update" that might be more-or-less useful in different situations:
- The user has updated data that feeds a view in the table using Mathesar, then wants to navigate easily to the view.
- The user recently updated the view definition (e.g., which columns, etc.) in Mathesar.
- The user bulk loaded more data into a table that feeds the view through a different client (e.g., `psql`), wants to easily navigate to the view.

I'm not sure which of these we should prioritize for the user.  Maybe all, but then what if other users are making heavy use of tables that feed views in the background?  The "recently updated views" would change constantly.

**Comment by pavish** [comment]
> access recently updated views through the left pane

Reading @mathemancer's comment, I think this should rather be recently _accessed_ views. This would be specific to each user. We can store this on the local storage for the alpha release, and think of user specific storage on the backend when we get to it.

**Comment by kgodey** [comment]
I've updated the issue to say that we'll show all views for now and update the design to handle hundreds of tables/views in #723. I've also updated #723 to point to the discussion on this issue.

I'm marking this as ready and moving to the backlog for @ghislaineguerin to take up when she has the time.

**Comment by kgodey** [comment]
Assigning to myself in case the discussion around #834 ends up necessitating a separate section for materialized views.

**Comment by ghislaineguerin** [comment]
Assigned to Kriti to add additional implementation details.

**Comment by kgodey** [comment]
I'm tracking creating implementation issues in #1027 so I'm closing this issue.
