### ISSUE TITLE
Support per-record currency types

### ISSUE THREAD

**Issue by kgodey** [mathesar-foundation/mathesar#656]
## Problem

Due to a misunderstanding in requirements, we accidentally ended up implementing a custom money type that can have a different currency in each record. Since we already have the backend for this, we might as well use it.

## Proposed solution

We need a design for using the multi-currency money type. It's similar to the existing money type with the following changes:
- Users should be able to set and change the currency on a per-record basis. There should be a currency picker to allow them to select from existing currencies.
- Users should be able to set the default currency for a column as a display option. We will pre-fill this currency for them to avoid repetitive data entry.
- Users can set the decimal precision of a column as a display option, but cannot set it on a per-record basis.

## Additional context

- #239 
- #655 
- #417 
- #647

**Comment by seancolsen** [comment]
Ok, I'm closing this then. Thanks for weighing in, @kgodey. I'll leave it to @mathemancer to open that separate issue as needed.
