### ISSUE TITLE
Setup API documentation and Postman collection

### ISSUE THREAD

**Issue by pavish** [mathesar-foundation/mathesar#69]
* Having a dedicated API documentation would make things easier for quick reference of our APIs as well as for anyone developing clients for Mathesar. Personal preference: [Redoc](https://github.com/Redocly/redoc)
* [Postman](https://www.postman.com) collections make it easier to store, query, test and share APIs. Having one would make development and debugging easier. (Optional - just an idea)

## Related Discussion
- #875

**Comment by ManishShah120** [comment]
Hi @pavish I too felt the need of this feature while trying to understand all the present API endpoints and its allowable parameters.  May be we can also think of [Swagger](https://swagger.io/)!

**Comment by seancolsen** [comment]
I'm closing this because it seems out of date. In 2023 we had a GSoC project to document the API, and that project made some slightly different decisions from what is specified in this ticket description.
