### ISSUE TITLE
For private class properties in TypeScript, use the `private` keyword instead of underscore prefix

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#729]
On a call today @pavish and I agreed that we should refactor TypeScript class properties prefixed with underscores to use the [`private` keyword](https://www.typescriptlang.org/docs/handbook/2/classes.html#private) instead of the underscore. 

For example, this...

```typescript
export class Columns implements Writable<TableColumnData> {
  _parentId: DBObjectEntry['id'];
  // ...
}
```

should be rewritten as...

```typescript
export class Columns implements Writable<TableColumnData> {
  private parentId: DBObjectEntry['id'];
  // ...
}
```

This refactoring is low-priority, but has the following benefits:

- More consistent with conventions within the TypeScript community.
- Visibility is enforced by the TS compiler.
- Some refactoring becomes a bit simpler. For example, if I want to change a private property to public, I only need to change one line.
- Allows us to distinguish between private and protected if we want.

**Comment by pavish** [comment]
@gagan2005 Thanks! I've assigned this issue to you. Let us know if you require any help from our end. Feel free to join our matrix channels: https://wiki.mathesar.org/community
