### ISSUE TITLE
Support for larger data sets

### ISSUE THREAD

**Issue by mathemancer** [mathesar-foundation/mathesar#736]
## Problem

For ease of use and implementation, we've made some decisions that will likely make performance a problem for large data sets.  

## Proposed solution

- We need to set up some large data sets, and do some performance profiling.
  - #83 should cover part of this.
- We need to analyze our methods of filtering and grouping.  These are likely to be performance drains at scale.
- We need to explore indexing commonly grouped columns (or allowing the user to do it)
  - It might be worth automatically analyzing usage patterns to offer suggestions, since many users will not understand implications of indexing columns.

**Comment by kgodey** [comment]
Closing this, too old, requirements are out of date. We can create a new issue if we need this functionality in the future.
