### ISSUE TITLE
Evaluate the possibility of using SvelteKit to build our component library

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#884]
I recently learned that one of the design goals of [SvelteKit](https://github.com/sveltejs/kit) is to help [build and publish component libraries](https://kit.svelte.dev/docs#packaging).

Check out this [JS Party podcast episode published a couple days ago](https://changelog.com/jsparty/205). At around 36:48, they begin to talk about using Svelte for building component libraries. Rich says:

> What I hoping is that the release of SvelteKit is going to make it much easier for people to build really high quality component libraries. And that's because SvelteKit, in addition to building applications, is a framework for building component libraries. I've used it for a couple of libraries so far and it's just a much much nicer workflow for building libraries than anything I've used in the past. So hopefully the release of SvelteKit is going to mean there's a bit of an explosion of component libraries.

This makes me wonder if we could replace Storybook with SvelteKit. Currently we're only using Storybook for the library components -- not for any Mathesar components. It's great having something _like_ Storybook, but Storybook itself can be kind of finicky. We [can't use TypeScript in it](https://github.com/centerofci/mathesar/issues/878). It doesn't seem to work with the Svelte dev tools browser extension. And it's errors and failures are quite opaque. At my previous job I found that Storybook made `npm update` a bit harder too. Most of the security audit failures came from packages required by Storybook, and I had some issues with dependency problems a couple times.

I think it would be worth exploring the possibility of using SvelteKit to build our component library. I'd want to take a stab at setting up a blank project and moving our component code into it to get a sense of the developer experience. Perhaps we'd want to wait until after SvelteKit 1.0 is release. But I'm not sure it would matter for this purpose because I get the sense that it's mostly stabilized and they're just ironing out small details at this point.

**Comment by pavish** [comment]
I'd rather wait until SvelteKit is stabilized. It took Svelte multiple iterations (And everything changed from v2 to v3) before it was stable enough for us to use. I'm sure SvelteKit would have a much smaller cycle, but I'd still like us not to rush into it.

We can wait until we are ready to split our component library into a repo & package of it's own (only after Mathesar's initial release), and then evaluate using SvelteKit and perhaps having a dedicated site for the component library which would make Storybook unnecessary.

**Comment by seancolsen** [comment]
Closing as I don't think this is important enough to track
